#!/usr/bin/env python3
"""Telegram Export Converter — convert between HTML and JSON exports.

Both directions in one module, with auto-detection of what the folder
contains:

  HTML -> JSON   Parses a Telegram HTML chat export (raw, fused,
                 compacted and/or enhanced — enhanced markup is
                 normalized back first) and writes a result.json
                 following Telegram Desktop's own JSON export schema
                 (https://core.telegram.org/import-export). Two modes:
                   * enriched (default): extra keys not present in the
                     official schema (call status texts, file names,
                     generator mark) are injected so no data is lost.
                   * faithful (--faithful): official keys only —
                     DESTRUCTIVE, that extra data is dropped, AND the
                     HTML-only pages/assets (messages*.html, css/, js/,
                     images/) are deleted so the folder ends up
                     matching a genuine JSON export's layout exactly.

  JSON -> HTML   Rebuilds the browsable messages*.html pages from a
                 result.json (official, generated by this tool, or a
                 result_enriched.json if that is all the folder has).
                 The JSON export lacks the static "web" assets of the
                 HTML one (css/, js/, images/), so they are embedded in
                 this module and written alongside the pages.

  Both present   When a folder holds BOTH exports of the same chat,
                 --enrich merges the extra fields recoverable from the
                 HTML into the official result.json (which holds data
                 the HTML lacks: from_id, edited dates, file sizes...)
                 -> result_enriched.json, touching neither original.

  Enriched only  When a folder holds ONLY a result_enriched.json (no
                 HTML, no official result.json), --downgrade strips
                 this tool's extra data back to a plain, official-
                 schema result.json — DESTRUCTIVE, same trade-off as
                 --faithful.

Media files are never copied: they are referenced by the same relative
paths (photos/..., voice_messages/...), which both export layouts share.

Fields that Telegram's HTML export simply does not contain cannot be
recovered when converting HTML -> JSON: numeric ids ("from_id",
"actor_id"), "edited" timestamps, media dimensions, mime types and
file sizes.

Usage:
    python telegram_export_converter.py <export_dir>            # auto
    python telegram_export_converter.py <export_dir> --to-json
                        [--faithful] [-o OUT.json] [--indent N | --compact]
    python telegram_export_converter.py <export_dir> --to-html
                        [--page-size SIZE] [--force]
    python telegram_export_converter.py <export_dir> --enrich [-o OUT.json]
    python telegram_export_converter.py <export_dir> --downgrade [-o OUT.json]

Must live next to telegram_export_fuser.py and
telegram_export_enhancer.py (it reuses their parsers).
"""

import argparse
import base64
import calendar
import html as htmllib
import json
import re
import shutil
import sys
import zlib
from datetime import datetime, timedelta, timezone
from pathlib import Path

from telegram_export_fuser import (
    DEFAULT_PAGE_SIZE, Message, chat_title, merge_messages, parse_export,
    parse_size, report_stage, write_pages,
)
from telegram_export_enhancer import (
    DURATION_RE, STATUS_RE, revert_media, revert_quotes,
)

GENERATOR = "Telegram Export Studio"

# ===========================================================================
# HTML -> JSON
# ===========================================================================

TEXT_DIV_RE = re.compile(r'<div class="text">\s*\n(.*?)\n\s*</div>',
                         re.DOTALL)
SERVICE_BODY_RE = re.compile(
    r'<div class="body details">\s*\n(.*?)\n\s*</div>', re.DOTALL)
TITLE_FULL_RE = re.compile(
    r'<div class="pull_right date details" title="'
    r'(\d{2})\.(\d{2})\.(\d{4}) (\d{2}):(\d{2}):(\d{2})'
    r'(?: UTC([+-]\d{2}):(\d{2}))?"')
REPLY_TO_RE = re.compile(
    r'<div class="reply_to details">.*?#go_to_message(\d+)', re.DOTALL)
PHOTO_RE = re.compile(r'<a class="photo_wrap[^"]*" href="([^"]+)"')
STICKER_RE = re.compile(r'<a class="sticker_wrap[^"]*" href="([^"]+)"')
VIDEO_HREF_RE = re.compile(r'<a class="video_file_wrap[^"]*" href="([^"]+)"')
VIDEO_THUMB_RE = re.compile(r'<img class="video_file" src="([^"]+)"')
MEDIA_LINK_RE = re.compile(
    r'<a class="media clearfix pull_left block_link ([\w-]+)"'
    r' href="([^"]+)"')
MEDIA_CALL_RE = re.compile(r'<div class="media clearfix pull_left media_call')
TITLE_BOLD_RE = re.compile(r'<div class="title bold">\s*\n(.*?)\n', re.DOTALL)
FORWARDED_FROM_RE = re.compile(
    r'<div class="forwarded body">\s*\n\s*<div class="from_name">\s*\n'
    r'\s*(.*?)\s*(?:<span class="date details"|\n)', re.DOTALL)
REACTIONS_OPEN_RE = re.compile(r'<span class="reactions">')
REACTION_EMOJI_RE = re.compile(r'<span class="emoji">\s*(.*?)\s*</span>',
                               re.DOTALL)
REACTION_WHO_RE = re.compile(r'<div class="initials"[^>]*title="([^"]+)"')
REACTION_COUNT_RE = re.compile(r'<span class="count">\s*(\d+)\s*</span>')

# inline formatting inside a text div -> MessageEntity, in document order
ENTITY_RE = re.compile(
    r'<a\s+href\s*=\s*"(?P<href>[^"]*)"[^>]*>(?P<atext>.*?)</a>'
    r'|<(?P<tag>strong|b|em|i|code|pre|u|s|strike|del)>'
    r'(?P<ttext>.*?)</(?P=tag)>'
    r'|<span class="spoiler">(?P<stext>.*?)</span>',
    re.DOTALL)
TAG_ENTITIES = {"strong": "bold", "b": "bold", "em": "italic", "i": "italic",
                "code": "code", "pre": "pre", "u": "underline",
                "s": "strikethrough", "strike": "strikethrough",
                "del": "strikethrough"}

# media_* CSS class of the HTML export -> media_type of Telegram's JSON
# (generic documents carry no media_type in the official schema)
MEDIA_TYPES = {
    "media_voice_message": "voice_message",
    "media_audio_file": "audio_file",
    "media_video": "video_message",
    "media_animation": "animation",
}

# status text of a call in the HTML export -> official discard_reason
CALL_REASONS = (("busy", "busy"), ("declined", "busy"),
                ("disconnect", "disconnect"),
                ("missed", "missed"), ("cancelled", "missed"))

# extra per-message keys of the enriched output that do NOT exist in
# Telegram's official JSON schema; the "faithful" mode strips them
ENRICHED_KEYS = ("status", "file_name")

# top-level folders the HTML export ships that a genuine JSON export never
# has (Telegram Desktop's own JSON export is just result.json + media
# folders) — removed by the faithful mode to match that layout exactly
ASSET_DIRS = ("css", "js", "images")


def _remove_html_assets(d: Path):
    """Delete the HTML-only pages and static assets (messages*.html,
    css/, js/, images/), leaving just result.json + the shared media
    folders — the faithful mode's destructive cleanup."""
    for f in d.glob("messages*.html"):
        f.unlink()
    for sub in ASSET_DIRS:
        shutil.rmtree(d / sub, ignore_errors=True)


def _guard_overwrite(out: Path, mark: str):
    """Refuse to overwrite a JSON file this tool did not generate (e.g.
    Telegram's own official export). Files carrying our top-level mark
    (generated_by / enriched_by) are ours and safe to regenerate."""
    if not out.exists():
        return
    try:
        existing = json.loads(out.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError, UnicodeDecodeError):
        existing = None
    if not (isinstance(existing, dict) and existing.get(mark) == GENERATOR):
        raise ValueError(
            f"Ya existe {out.name} en la carpeta y no lo generó esta "
            "herramienta — sobrescribirlo destruiría el export JSON "
            "original. Usa -o para elegir otro archivo de salida.")


def plain_text(inner_html: str) -> str:
    """Inner HTML -> plain text: <br> to newline, tags out, entities in."""
    text = re.sub(r"<br\s*/?>", "\n", inner_html)
    text = re.sub(r"<[^>]+>", "", text)
    return htmllib.unescape(text)


def text_entities(inner_html: str):
    """Inner HTML of a text div -> list of MessageEntity dicts
    ({"type", "text", ...}), plain runs included as type "plain"."""
    entities = []

    def add_plain(segment):
        text = plain_text(segment)
        if text:
            entities.append({"type": "plain", "text": text})

    pos = 0
    for m in ENTITY_RE.finditer(inner_html):
        add_plain(inner_html[pos:m.start()])
        if m.group("href") is not None:
            href = m.group("href")
            text = plain_text(m.group("atext"))
            if href.lower().endswith((".tgs", ".webp", ".webm")):
                # custom emoji rendered as a link to the sticker file
                entities.append({"type": "custom_emoji", "text": text,
                                 "document_id": href})
            elif text == href:
                entities.append({"type": "link", "text": text})
            else:
                entities.append({"type": "text_link", "text": text,
                                 "href": href})
        elif m.group("tag"):
            entities.append({"type": TAG_ENTITIES[m.group("tag")],
                             "text": plain_text(m.group("ttext"))})
        else:
            entities.append({"type": "spoiler",
                             "text": plain_text(m.group("stext"))})
        pos = m.end()
    add_plain(inner_html[pos:])
    return entities


def entities_to_text(entities):
    """MessageEntity list -> the official "text" value: a plain string
    when there is no formatting, otherwise a mixed array where plain
    entities are unwrapped to bare strings."""
    if not entities:
        return ""
    if len(entities) == 1 and entities[0]["type"] == "plain":
        return entities[0]["text"].strip()
    return [e["text"] if e["type"] == "plain" else e for e in entities]


def _local_offsets(year: int):
    """UTC offsets of the system timezone in winter and summer."""
    return {datetime(year, 1, 15, 12).astimezone().utcoffset(),
            datetime(year, 7, 15, 12).astimezone().utcoffset()}


def parse_date(block: str):
    """Date title of a message -> (iso, unixtime_str_or_None).

    Telegram Desktop stamps every message with the timezone's STANDARD
    offset (e.g. "UTC+01:00" even in summer), while the wall-clock time
    shown is the real, DST-aware local time. If the labelled offset
    belongs to the timezone this machine is in, interpret the date with
    the full local timezone (DST included) so the unixtime matches the
    one in Telegram's own JSON export; otherwise fall back to the
    labelled offset as-is (possibly one hour off during DST).
    """
    m = TITLE_FULL_RE.search(block)
    if not m:
        return None, None
    dd, mo, yy, hh, mi, ss = (int(g) for g in m.groups()[:6])
    date = datetime(yy, mo, dd, hh, mi, ss)
    oh, om = m.group(7), m.group(8)
    if oh is None:
        return date.isoformat(), None
    sign = -1 if oh.startswith("-") else 1
    label = timedelta(hours=int(oh), minutes=sign * int(om))
    if label in _local_offsets(yy):
        stamped = date.astimezone()  # naive -> DST-aware local time
    else:
        stamped = date.replace(tzinfo=timezone(label))
    return date.isoformat(), str(int(stamped.timestamp()))


def duration_from(text: str):
    """'21 seconds' / 'Incoming (64 seconds)' / '0:07' / '(1:02:35)'
    -> seconds; None when the text holds no duration."""
    m = re.search(r"(\d+)\s*seconds?", text)
    if m:
        return int(m.group(1))
    m = (re.search(r"\((\d+(?::\d{1,2}){1,2})\)", text)
         or re.fullmatch(r"(\d+(?::\d{1,2}){1,2})", text.strip()))
    if not m:
        return None
    secs = 0
    for p in m.group(1).split(":"):
        secs = secs * 60 + int(p)
    return secs


def extract_media(block: str):
    """Media references of one message block -> dict of JSON fields."""
    m = PHOTO_RE.search(block)
    if m:
        return {"photo": m.group(1)}

    m = STICKER_RE.search(block)
    if m:
        return {"media_type": "sticker", "file": m.group(1)}

    m = VIDEO_HREF_RE.search(block)
    if m:
        out = {"media_type": "video_file", "file": m.group(1)}
        tm = VIDEO_THUMB_RE.search(block)
        if tm:
            out["thumbnail"] = tm.group(1)
        dm = DURATION_RE.search(block)
        if dm:
            secs = duration_from(dm.group(1).strip())
            if secs is not None:
                out["duration_seconds"] = secs
        return out

    m = MEDIA_LINK_RE.search(block)
    if m:
        css, href = m.groups()
        out = {"file": href}
        media_type = MEDIA_TYPES.get(css)
        if media_type:
            out["media_type"] = media_type
        tm = TITLE_BOLD_RE.search(block)
        sm = STATUS_RE.search(block)
        if sm:
            status = plain_text(sm.group(1)).strip()
            secs = duration_from(status)
            if secs is not None:
                out["duration_seconds"] = secs
            else:
                out["status"] = status
        if media_type is None and tm:
            out["file_name"] = plain_text(tm.group(1)).strip()
        return out

    return {}


def extract_reactions(block: str):
    """Reactions span of one message -> official-style reactions list."""
    m = REACTIONS_OPEN_RE.search(block)
    if not m:
        return None
    reactions = []
    chunks = block[m.end():].split('<span class="reaction')[1:]
    for chunk in chunks:
        em = REACTION_EMOJI_RE.search(chunk)
        if not em:
            continue
        who = [htmllib.unescape(w) for w in REACTION_WHO_RE.findall(chunk)]
        cm = REACTION_COUNT_RE.search(chunk)
        reactions.append({
            "type": "emoji",
            "count": int(cm.group(1)) if cm else max(len(who), 1),
            "emoji": htmllib.unescape(em.group(1)),
            "recent": [{"from": w} for w in who],
        })
    return reactions or None


def message_to_dict(msg):
    """One fuser Message -> JSON-serializable dict."""
    # enhanced exports: normalize quotes / inline players back to the
    # original Telegram markup so a single set of patterns applies
    block = revert_media(revert_quotes(msg.html))

    entry = {"id": msg.msg_id,
             "type": msg.kind if msg.kind == "service" else "message"}
    date_iso, date_unix = parse_date(block)
    if date_iso:
        entry["date"] = date_iso
        if date_unix:
            entry["date_unixtime"] = date_unix
    sender = htmllib.unescape(msg.sender) if msg.sender else None

    if msg.kind == "service":
        if sender:
            entry["actor"] = sender
        bm = SERVICE_BODY_RE.search(block)
        entry["text"] = plain_text(bm.group(1)).strip() if bm else ""
        entry["text_entities"] = []
        return entry

    # calls appear as regular messages in the HTML export but are
    # service messages with action phone_call in Telegram's JSON
    if MEDIA_CALL_RE.search(block):
        entry["type"] = "service"
        if sender:
            entry["actor"] = sender
        entry["action"] = "phone_call"
        sm = STATUS_RE.search(block)
        status = plain_text(sm.group(1)).strip() if sm else ""
        secs = duration_from(status)
        if secs is not None:
            entry["duration_seconds"] = secs
            entry["discard_reason"] = "hangup"
        else:
            low = status.lower()
            for needle, reason in CALL_REASONS:
                if needle in low:
                    entry["discard_reason"] = reason
                    break
        if status:
            entry["status"] = status
        entry["text"] = ""
        entry["text_entities"] = []
        return entry

    if sender:
        entry["from"] = sender

    fm = FORWARDED_FROM_RE.search(block)
    if fm:
        entry["forwarded_from"] = htmllib.unescape(
            re.sub(r"\s+", " ", fm.group(1)).strip())

    rm = REPLY_TO_RE.search(block)
    if rm:
        entry["reply_to_message_id"] = int(rm.group(1))

    entry.update(extract_media(block))

    tm = TEXT_DIV_RE.search(block)
    entities = text_entities(tm.group(1)) if tm else []
    entry["text"] = entities_to_text(entities)
    entry["text_entities"] = entities

    reactions = extract_reactions(block)
    if reactions:
        entry["reactions"] = reactions
    return entry


def to_json(export_dir, out_file=None, indent=1, faithful=False):
    """HTML -> JSON. Parse export_dir and write the JSON file.

    faithful=True keeps ONLY the keys of Telegram's official JSON
    schema — a destructive conversion: the extra data preserved by the
    default enriched mode (call direction/status texts, file names,
    the generator mark) is dropped, AND the HTML-only pages and static
    assets (messages*.html, css/, js/, images/) are deleted so the
    folder ends up matching Telegram's own JSON export layout exactly.
    """
    d = Path(export_dir).resolve()
    report_stage("scan", name=d.name)
    messages, header_html, sender_headers = parse_export(d)

    # single-export "merge": sorts by id and dedups anchored service blocks
    merged = merge_messages([(messages, header_html, sender_headers)])

    report_stage("convert")
    entries = [message_to_dict(m) for m in merged]
    real = sum(1 for m in merged if m.msg_id > 0)

    if faithful:
        for e in entries:
            for k in ENRICHED_KEYS:
                e.pop(k, None)
        doc = {"name": chat_title(header_html) or "", "messages": entries}
    else:
        doc = {"name": chat_title(header_html) or "",
               "generated_by": GENERATOR,
               "messages": entries}

    out = Path(out_file).resolve() if out_file else d / "result.json"
    if out_file is None:
        _guard_overwrite(out, "generated_by")
    report_stage("write")
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, indent=indent)
        f.write("\n")

    removed_assets = False
    if faithful and out_file is None:
        _remove_html_assets(d)
        removed_assets = True

    print(f"Converted {real} messages from {d}")
    print(f"Wrote {out} ({out.stat().st_size // 1024} KB)")
    if removed_assets:
        print("Removed the HTML pages and web assets "
              "(messages*.html, css/, js/, images/)")
    return {
        "messages": real,
        "out_file": str(out),
        "out_dir": str(out.parent),
        "removed_assets": removed_assets,
    }


# ===========================================================================
# JSON -> HTML
# ===========================================================================

HEADER_TEMPLATE = """<!DOCTYPE html>
<html>

 <head>

  <meta charset="utf-8"/>
<title>Exported Data</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>

  <link href="css/style.css" rel="stylesheet"/>

  <script src="js/script.js" type="text/javascript">

  </script>

 </head>

 <body onload="CheckLocation();">

  <div class="page_wrap">

   <div class="page_header">

    <div class="content">

     <div class="text bold">
{title}
     </div>

    </div>

   </div>

   <div class="page_body chat_page">

    <div class="history">"""

# Telegram Desktop's peer color mapping: color = LOOKUP[peer_id % 7]
USERPIC_COLORS = [0, 7, 4, 1, 6, 3, 5]

# MessageEntity type -> HTML tag pair of the Telegram HTML export
ENTITY_TAGS = {"bold": ("<strong>", "</strong>"),
               "italic": ("<em>", "</em>"),
               "code": ("<code>", "</code>"),
               "pre": ("<pre>", "</pre>"),
               "underline": ("<u>", "</u>"),
               "strikethrough": ("<s>", "</s>"),
               "spoiler": ('<span class="spoiler">', "</span>")}


def esc(text: str) -> str:
    return htmllib.escape(str(text), quote=False)


def initials_of(name: str) -> str:
    words = [w for w in name.split() if w]
    return "".join(w[0] for w in words[:2]).upper() or "?"


def userpic_index(entry: dict) -> int:
    """Stable 1..8 color index: Telegram's own mapping when a numeric
    from_id/actor_id is available, a name hash otherwise."""
    peer = entry.get("from_id") or entry.get("actor_id") or ""
    digits = re.sub(r"\D", "", str(peer))
    if digits:
        key = int(digits)
    else:
        name = entry.get("from") or entry.get("actor") or "?"
        key = sum(name.encode("utf-8"))
    return USERPIC_COLORS[key % 7] + 1


def date_title(date: datetime, unixtime) -> str:
    """'24.01.2026 17:54:24 UTC+01:00' — the offset is derived from the
    unixtime, so it is the REAL offset of the message (DST included)."""
    base = date.strftime("%d.%m.%Y %H:%M:%S")
    if not unixtime:
        return base
    off = calendar.timegm(date.timetuple()) - int(unixtime)
    sign = "+" if off >= 0 else "-"
    off = abs(off)
    return f"{base} UTC{sign}{off // 3600:02d}:{off % 3600 // 60:02d}"


def fmt_duration(seconds) -> str:
    """21 -> '0:21', 3723 -> '1:02:03' (Telegram HTML style)."""
    s = int(seconds)
    if s >= 3600:
        return f"{s // 3600}:{s % 3600 // 60:02d}:{s % 60:02d}"
    return f"{s // 60}:{s % 60:02d}"


def human_size(n) -> str:
    n = float(n)
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024 or unit == "GB":
            return f"{n:.0f} B" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024
    return f"{n:.1f} GB"


def entities_html(entry: dict) -> str:
    """Official "text"/"text_entities" -> the inline HTML of a text div."""
    parts = entry.get("text_entities")
    if parts is None:
        text = entry.get("text", "")
        parts = [text] if isinstance(text, str) else text
    out = []
    for p in parts:
        if isinstance(p, str) or p.get("type") == "plain":
            text = p if isinstance(p, str) else p["text"]
            out.append(esc(text).replace("\n", "<br>"))
            continue
        kind, text = p.get("type"), esc(p.get("text", ""))
        if kind == "link":
            out.append(f'<a href="{p["text"]}">{text}</a>')
        elif kind == "text_link":
            out.append(f'<a href="{p.get("href", "")}">{text}</a>')
        elif kind == "custom_emoji":
            out.append(f'<a href="{p.get("document_id", "")}">{text}</a>')
        elif kind in ENTITY_TAGS:
            o, c = ENTITY_TAGS[kind]
            out.append(o + text.replace("\n", "<br>") + c)
        else:  # mention, hashtag, phone, email, ... -> plain text
            out.append(text.replace("\n", "<br>"))
    return "".join(out)


def media_html(entry: dict) -> str:
    """Media fields of a JSON message -> the media_wrap block, or ''."""
    photo = entry.get("photo")
    if photo:
        style = ""
        w, h = entry.get("width"), entry.get("height")
        if w and h:
            scale = min(260 / max(int(w), int(h)), 1)
            style = (f' style="width: {int(int(w) * scale)}px; '
                     f'height: {int(int(h) * scale)}px"')
        return (f'       <div class="media_wrap clearfix">\n'
                f'        <a class="photo_wrap clearfix pull_left" '
                f'href="{photo}">\n'
                f'         <img class="photo" src="{photo}"{style}/>\n'
                f'        </a>\n'
                f'       </div>\n')

    media_type = entry.get("media_type")
    file = entry.get("file")

    if media_type == "sticker" and file:
        thumb = entry.get("thumbnail") or file
        return (f'       <div class="media_wrap clearfix">\n'
                f'        <a class="sticker_wrap clearfix pull_left" '
                f'href="{file}">\n'
                f'         <img class="sticker" src="{thumb}"/>\n'
                f'        </a>\n'
                f'       </div>\n')

    if media_type in ("video_file", "video_message", "animation") and file:
        thumb = entry.get("thumbnail") or f"{file}_thumb.jpg"
        dur = entry.get("duration_seconds")
        dur_div = (f'         <div class="video_duration">\n'
                   f'{fmt_duration(dur)}\n'
                   f'         </div>\n' if dur is not None else "")
        return (f'       <div class="media_wrap clearfix">\n'
                f'        <a class="video_file_wrap clearfix pull_left" '
                f'href="{file}">\n'
                f'         <div class="video_play_bg">\n'
                f'          <div class="video_play">\n'
                f'          </div>\n'
                f'         </div>\n'
                f'{dur_div}'
                f'         <img class="video_file" src="{thumb}"/>\n'
                f'        </a>\n'
                f'       </div>\n')

    if file:
        if media_type == "voice_message":
            css, title = "media_voice_message", "Voice message"
        elif media_type == "audio_file":
            css = "media_audio_file"
            title = entry.get("title") or "Audio file"
        else:
            css = "media_file"
            title = (entry.get("file_name")
                     or file.rsplit("/", 1)[-1])
        dur = entry.get("duration_seconds")
        status = (entry.get("status")
                  or (fmt_duration(dur) if dur is not None else None)
                  or (human_size(entry["file_size"])
                      if entry.get("file_size") else None))
        status_div = (f'          <div class="status details">\n'
                      f'{esc(status)}\n'
                      f'          </div>\n' if status else "")
        return (f'       <div class="media_wrap clearfix">\n'
                f'        <a class="media clearfix pull_left block_link '
                f'{css}" href="{file}">\n'
                f'         <div class="fill pull_left">\n'
                f'         </div>\n'
                f'         <div class="body">\n'
                f'          <div class="title bold">\n'
                f'{esc(title)}\n'
                f'          </div>\n'
                f'{status_div}'
                f'         </div>\n'
                f'        </a>\n'
                f'       </div>\n')
    return ""


def call_html(entry: dict) -> str:
    """A phone_call service entry -> the media_call block the HTML
    export uses (calls are regular messages there)."""
    status = entry.get("status")  # enriched JSON keeps the exact text
    if not status:
        dur = entry.get("duration_seconds")
        reason = entry.get("discard_reason")
        if dur is not None:
            status = f"({int(dur)} seconds)"
        else:
            status = {"missed": "Missed", "busy": "Busy",
                      "disconnect": "Disconnected"}.get(reason, "Cancelled")
    ok = " success" if entry.get("duration_seconds") is not None else ""
    title = entry.get("actor") or "Call"
    return (f'       <div class="media_wrap clearfix">\n'
            f'        <div class="media clearfix pull_left media_call{ok}">\n'
            f'         <div class="fill pull_left">\n'
            f'         </div>\n'
            f'         <div class="body">\n'
            f'          <div class="title bold">\n'
            f'{esc(title)}\n'
            f'          </div>\n'
            f'          <div class="status details">\n'
            f'{esc(status)}\n'
            f'          </div>\n'
            f'         </div>\n'
            f'        </div>\n'
            f'       </div>\n')


def reactions_html(entry: dict) -> str:
    spans = []
    for r in entry.get("reactions") or []:
        pics = []
        for who in r.get("recent") or []:
            name = who.get("from") or "?"
            pics.append(
                f'          <div class="userpic userpic'
                f'{userpic_index(who)}" '
                f'style="width: 20px; height: 20px">\n'
                f'           <div class="initials" '
                f'style="line-height: 20px" title="{esc(name)}">\n'
                f'{initials_of(name)}\n'
                f'           </div>\n'
                f'          </div>\n')
        spans.append(
            f'        <span class="reaction">\n'
            f'         <span class="emoji">\n'
            f'{esc(r.get("emoji", ""))}\n'
            f'         </span>\n'
            f'         <span class="userpics">\n'
            f'{"".join(pics)}'
            f'         </span>\n'
            f'        </span>\n')
    if not spans:
        return ""
    return (f'       <span class="reactions">\n'
            f'{"".join(spans)}'
            f'       </span>\n')


def userpic_html(entry: dict, sender: str) -> str:
    return (f'      <div class="pull_left userpic_wrap">\n'
            f'       <div class="userpic userpic{userpic_index(entry)}" '
            f'style="width: 42px; height: 42px">\n'
            f'        <div class="initials" style="line-height: 42px">\n'
            f'{initials_of(sender)}\n'
            f'        </div>\n'
            f'       </div>\n'
            f'      </div>\n')


def from_name_html(sender: str) -> str:
    return (f'       <div class="from_name">\n'
            f'{esc(sender)}\n'
            f'       </div>\n')


def build_block(entry: dict, joined: bool):
    """One JSON message -> (html_block, kind, sender, date)."""
    mid = entry["id"]
    date = (datetime.fromisoformat(entry["date"])
            if entry.get("date") else None)
    is_call = entry.get("action") == "phone_call"

    if entry.get("type") == "service" and not is_call:
        text = entry.get("text")
        if isinstance(text, list):
            text = "".join(p if isinstance(p, str) else p.get("text", "")
                           for p in text)
        if not text:
            actor = entry.get("actor") or ""
            action = entry.get("action") or "service message"
            text = f"{actor} {action.replace('_', ' ')}".strip()
        block = (f'     <div class="message service" id="message{mid}">\n\n'
                 f'      <div class="body details">\n'
                 f'{esc(text)}\n'
                 f'      </div>\n\n'
                 f'     </div>')
        return block, "service", None, date

    sender = entry.get("from") or entry.get("actor") or "?"
    time_div = (f'       <div class="pull_right date details" '
                f'title="{date_title(date, entry.get("date_unixtime"))}">\n'
                f'{date.strftime("%H:%M")}\n'
                f'       </div>\n') if date else ""

    body = []
    reply = entry.get("reply_to_message_id")
    if reply:
        body.append(
            f'       <div class="reply_to details">\n'
            f'In reply to <a href="#go_to_message{reply}" '
            f'onclick="return GoToMessage({reply})">this message</a>\n'
            f'       </div>\n')

    if is_call:
        body.append(call_html(entry))
    else:
        media = media_html(entry)
        text_inner = entities_html(entry)
        text_div = (f'       <div class="text">\n'
                    f'{text_inner}\n'
                    f'       </div>\n') if text_inner else ""
        fwd = entry.get("forwarded_from")
        if fwd:
            inner = "".join(
                "  " + line if line else line
                for line in (media + text_div).splitlines(keepends=True))
            body.append(
                f'       <div class="forwarded body">\n'
                f'        <div class="from_name">\n'
                f'{esc(fwd)}\n'
                f'        </div>\n'
                f'{inner}'
                f'       </div>\n')
        else:
            body.append(media + text_div)
    body.append(reactions_html(entry))

    joined_cls = " joined" if joined else ""
    userpic = "" if joined else userpic_html(entry, sender)
    name_div = "" if joined else from_name_html(sender)
    block = (f'     <div class="message default clearfix{joined_cls}" '
             f'id="message{mid}">\n'
             f'{userpic}'
             f'      <div class="body">\n'
             f'{time_div}'
             f'{name_div}'
             f'{"".join(body)}'
             f'      </div>\n'
             f'     </div>')
    return block, "default", sender, date


def load_chat(json_file: Path) -> dict:
    doc = json.loads(json_file.read_text(encoding="utf-8"))
    if "chats" in doc:
        raise ValueError(
            "Este result.json es una exportación completa de la cuenta "
            "(contiene varios chats), no un chat individual. De momento "
            "solo se soportan exports de un chat concreto.")
    if "messages" not in doc:
        raise ValueError("El JSON no contiene la clave 'messages' — no "
                         "parece un export de chat de Telegram.")
    return doc


def write_assets(out_dir: Path):
    for rel, b64 in ASSETS.items():
        dest = out_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(base64.b64decode(b64))


def from_json(export_dir, page_size=None, force=False):
    """JSON -> HTML. result.json (or, if absent, result_enriched.json)
    in export_dir -> messages*.html + web assets, in place (the media
    folders already live there)."""
    d = Path(export_dir).resolve()
    json_file = d / "result.json"
    if not json_file.is_file():
        json_file = d / "result_enriched.json"
    if not json_file.is_file():
        raise ValueError(
            f"No se encontró result.json ni result_enriched.json en {d}")
    if not force and list(d.glob("messages*.html")):
        raise ValueError(
            "La carpeta ya contiene messages*.html — se sobrescribirían. "
            "Usa --force (o confirma en la interfaz) para regenerarlos.")

    report_stage("scan", name=d.name)
    doc = load_chat(json_file)
    entries = [e for e in doc["messages"] if isinstance(e.get("id"), int)]

    report_stage("convert")
    messages = []
    sender_headers = {}
    prev_sender, prev_day = None, None
    for i, e in enumerate(entries):
        if i % 100 == 0:
            report_stage("convert", frac=i / max(len(entries), 1))
        date = (datetime.fromisoformat(e["date"]) if e.get("date") else None)
        day = date.date() if date else None
        joined = (e.get("type") != "service"
                  and e.get("action") != "phone_call"
                  and e.get("from") is not None
                  and e.get("from") == prev_sender
                  and day is not None and day == prev_day)
        block, kind, sender, date = build_block(e, joined)
        if kind == "default":
            prev_sender, prev_day = sender, day
            if sender and sender not in sender_headers:
                sender_headers[sender] = (userpic_html(e, sender),
                                          from_name_html(sender).strip())
        else:
            prev_sender = None
        messages.append(Message(
            msg_id=e["id"], kind=kind, joined=joined, date=date,
            sender=sender, html=block, source=d))

    title = doc.get("name") or "Exported Data"
    header_html = HEADER_TEMPLATE.format(title=esc(title))
    write_assets(d)
    page_bytes = parse_size(page_size or DEFAULT_PAGE_SIZE)
    written = write_pages(messages, header_html, d, page_bytes,
                          sender_headers)
    print(f"Rebuilt {len(written)} page(s) from {json_file.name} "
          f"({len(messages)} messages) in {d}")
    return {
        "messages": len(messages),
        "pages": written,
        "out_dir": str(d),
    }


# ===========================================================================
# Both formats present: enrich the official JSON with the HTML's extras
# ===========================================================================

def enrich_json(export_dir, out_file=None):
    """Folder with BOTH exports: merge the extra fields recoverable from
    the HTML into the official result.json -> result_enriched.json.
    Neither original file is touched; official values always win."""
    d = Path(export_dir).resolve()
    json_file = d / "result.json"
    if not json_file.is_file():
        raise ValueError(f"No se encontró result.json en {d}")
    if not list(d.glob("messages*.html")):
        raise ValueError(f"No se encontró messages.html en {d}")

    report_stage("scan", name=d.name)
    doc = load_chat(json_file)
    parsed = parse_export(d)
    merged = merge_messages([parsed])

    report_stage("convert")
    html_entries = {}
    for m in merged:
        e = message_to_dict(m)
        html_entries[e["id"]] = e

    added_fields = 0
    added_msgs = 0
    by_id = {}
    for m in doc["messages"]:
        if isinstance(m.get("id"), int):
            by_id[m["id"]] = m
    for mid, e in html_entries.items():
        m = by_id.get(mid)
        if m is None:
            if mid > 0:  # message present in the HTML but not in the JSON
                doc["messages"].append(e)
                added_msgs += 1
            continue
        for k, v in e.items():
            if k not in m:
                m[k] = v
                added_fields += 1
    if added_msgs:
        doc["messages"].sort(
            key=lambda m: m.get("id") if isinstance(m.get("id"), int) else 0)
    doc["enriched_by"] = GENERATOR

    out = Path(out_file).resolve() if out_file else d / "result_enriched.json"
    if out_file is None:
        _guard_overwrite(out, "enriched_by")
    report_stage("write")
    with out.open("w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, indent=1)
        f.write("\n")
    print(f"Enriched {len(doc['messages'])} messages "
          f"(+{added_fields} fields, +{added_msgs} messages from HTML)")
    print(f"Wrote {out} ({out.stat().st_size // 1024} KB)")
    return {
        "messages": len(doc["messages"]),
        "added_fields": added_fields,
        "added_msgs": added_msgs,
        "out_file": str(out),
        "out_dir": str(d),
    }


def downgrade_json(export_dir, out_file=None):
    """Folder with ONLY a result_enriched.json (no HTML, no official
    result.json): strip this tool's extras (ENRICHED_KEYS, the
    enriched_by/generated_by marks) back to a plain, official-schema
    result.json. DESTRUCTIVE: the recovered call status texts, file
    names etc. are dropped, same as the faithful HTML -> JSON mode."""
    d = Path(export_dir).resolve()
    src = d / "result_enriched.json"
    if not src.is_file():
        raise ValueError(f"No se encontró result_enriched.json en {d}")

    report_stage("scan", name=d.name)
    doc = json.loads(src.read_text(encoding="utf-8"))
    doc.pop("enriched_by", None)
    doc.pop("generated_by", None)
    report_stage("convert")
    for e in doc.get("messages", []):
        for k in ENRICHED_KEYS:
            e.pop(k, None)

    out = Path(out_file).resolve() if out_file else d / "result.json"
    if out_file is None:
        _guard_overwrite(out, "generated_by")
    report_stage("write")
    with out.open("w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, indent=1)
        f.write("\n")

    count = len(doc.get("messages", []))
    print(f"Downgraded {count} messages to the official format")
    print(f"Wrote {out} ({out.stat().st_size // 1024} KB)")
    return {
        "messages": count,
        "out_file": str(out),
        "out_dir": str(d),
    }


# ===========================================================================
# Detection & CLI
# ===========================================================================

def detect_formats(export_dir) -> dict:
    """What does the folder contain? ->
    {"html": bool, "json": bool, "enriched": bool}."""
    d = Path(export_dir)
    return {"html": bool(list(d.glob("messages*.html"))),
            "json": (d / "result.json").is_file(),
            "enriched": (d / "result_enriched.json").is_file()}


def main():
    ap = argparse.ArgumentParser(
        description="Convert a Telegram chat export between HTML and JSON "
                    "(both directions, auto-detected), or enrich the "
                    "official JSON with the extra data of the HTML export. "
                    "Media files are never copied.")
    ap.add_argument("export", help="export folder (HTML, JSON or both)")
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--to-json", action="store_true",
                      help="force HTML -> JSON")
    mode.add_argument("--to-html", action="store_true",
                      help="force JSON -> HTML")
    mode.add_argument("--enrich", action="store_true",
                      help="the folder holds BOTH exports: merge the "
                           "HTML's extra data into the official JSON "
                           "(-> result_enriched.json)")
    mode.add_argument("--downgrade", action="store_true",
                      help="the folder holds ONLY a result_enriched.json: "
                           "strip this tool's extra data back to the "
                           "official result.json. DESTRUCTIVE.")
    ap.add_argument("-o", "--output", default=None,
                    help="output JSON file for --to-json / --enrich / "
                         "--downgrade (default: result.json / "
                         "result_enriched.json inside the export folder)")
    ap.add_argument("--faithful", action="store_true",
                    help="HTML -> JSON only. DESTRUCTIVE: keep only the "
                         "keys of Telegram's official JSON schema, "
                         "dropping the extra data preserved by the "
                         "default enriched mode (call status texts, "
                         "file names, generator mark)")
    group = ap.add_mutually_exclusive_group()
    group.add_argument("--indent", type=int, default=1,
                       help="HTML -> JSON: indentation level (default: 1)")
    group.add_argument("--compact", action="store_true",
                       help="HTML -> JSON: single-line JSON")
    ap.add_argument("-s", "--page-size", default=DEFAULT_PAGE_SIZE,
                    help="JSON -> HTML: approximate size of each "
                         "messagesN.html page, e.g. 500KB, 2MB; 0 = "
                         f"single file (default: {DEFAULT_PAGE_SIZE})")
    ap.add_argument("-f", "--force", action="store_true",
                    help="JSON -> HTML: overwrite existing messages*.html")
    args = ap.parse_args()

    export_dir = Path(args.export).resolve()
    if not export_dir.is_dir():
        sys.exit(f"error: {export_dir} is not a directory")

    found = detect_formats(export_dir)
    if not (args.to_json or args.to_html or args.enrich or args.downgrade):
        if found["html"] and found["json"]:
            sys.exit(
                "error: la carpeta contiene A LA VEZ el export HTML y el "
                "JSON. Convertir de nuevo no aporta nada; lo útil es "
                "enriquecer el JSON oficial con los datos extra del HTML: "
                "vuelve a ejecutar con --enrich (o elige la dirección con "
                "--to-json / --to-html --force).")
        if found["html"]:
            args.to_json = True
        elif found["json"] or found["enriched"]:
            args.to_html = True
        else:
            sys.exit(f"error: {export_dir} no contiene messages.html, "
                     "result.json ni result_enriched.json")

    try:
        if args.downgrade:
            if not found["enriched"]:
                sys.exit(f"error: no hay result_enriched.json en "
                         f"{export_dir}")
            downgrade_json(export_dir, args.output)
        elif args.enrich:
            enrich_json(export_dir, args.output)
        elif args.to_json:
            if not found["html"]:
                sys.exit(f"error: no hay messages*.html en {export_dir}")
            to_json(export_dir, args.output,
                    indent=None if args.compact else args.indent,
                    faithful=args.faithful)
        else:
            if not (found["json"] or found["enriched"]):
                sys.exit(f"error: no hay result.json ni "
                         f"result_enriched.json en {export_dir}")
            from_json(export_dir, args.page_size, force=args.force)
    except ValueError as e:
        sys.exit(f"error: {e}")


# ---------------------------------------------------------------------------
# Embedded web assets of a Telegram HTML export (css/, js/, images/),
# zlib-compressed JSON {relative_path: base64_content}. Regenerable from
# any Telegram HTML export with tools/pack_assets.py.
# ---------------------------------------------------------------------------

ASSETS_BLOB = "eNrkvWnTosq2LvpXdqyv3tgCYncidsSlVVBQFFH4ckNBaQRBURHOn78jscP21bdqrXXO3nPOmlXlK2TmyJGjfcbI//0PM47L8Tb15/8Jf/rH//qPf+hBczkf0nVWCW2BoezZmE8Nwt/1XCrpJVgHfSa0jP1spdQElkvNtr2XVCeZM9RKrdD+zKVVfVzNxDRx1bbmTccDR+CsFD5bGkMhFpYHXCf8pT48fk/gtd10LO+N1sjtcnw6HfNxl3P8WdvwrZbv6cPD2JiIS/iu023LzmwlbU1Cg+/pMMeoCb8yqy3uZ4Fpz2/nt7UILTIIB4O5VySWOn/fmxEDv8vQGz1QYqFNp8YwsU2C35rMdd1G0NxZDB7oYzyatZc1gcP9WXDYdzkcxuK9WXpgZ0Q1mxEHx4S1KkQTNwPfN126Z0xMt9tC32tmZov3DDWWmRUmM0G+zus827RjtAYRzB1oKSIaYkDP+zlk00nkwxqqEjO6/EwnmvGsItQERvbkTMDlVuFnML8pYaWzirYzGBzWe9ibHvyM0KuGJwYyC/NxYXyGdmcVcWlMhK0Z8MvpRMtgnNMcclolZlCYL8zVrNCxPgF6tMR4RsibK0/gjhlY0QzGka7vj6fjqt8dO/50bIUWCz8bkpjk2biccZiUXb5XQfPojsXUGPObnku7ZqA50xR3Zq3ksi6LaKawngrMNSl8J3/2Og95P2s1U1iHJ2VSdv1cdHRiuzKDJj4LlG2BfoE81nHDK9IPxmlpaXciwv74uJmFttymyeu7mgTwZADjVGAejjUZ7HtP91RO5o+0hs952Gsa8U5kMJRnjDW/SMc5g4fG2F9N23DGWlXgo9ELnqBhHMcHvsPQ8wsF63QDOTbQmQ18shfwgQXrENqXOQAvVDFjXEVnwhUY4UrbwM+mYzGatXxsrob2tOUvgQa73kd7X9hftjBWS3MQ3wE9sSl7OgNuNbHGh3hCHHxjpRTPLLyTh3nRMH/jup4Vjc9ahwWsEdHj2ffT49jX9+tjy59UQOZMqML3X++/kf+rPzlbUgJyI7nKjnAH53llaM2cB4UWV3h/ge9UndTH8pUn2wN/3la2QE8PeMABubZH5wTkw+4iG+7mratROKsYSJ5c96ilkbD3SwPkJYyPTcdNkMtAn2AAPHCIjnxyM0/gIx7xXFHm7E3CPz8bTCeOb1z3rNYd+zuYJwnrOBT20oX1bIyKuLdAjnfH17UaJ+pd12pFRnsQHp+nCnwtwpxhni4O52CAzQjs8Ryosi8HI7Kw945BaIsp8BE6jwJTvfBvgacroGOAv+CMsnZSlJ9F3SW0eNxqNd6ecYmhnOkYT2CPMB2dkVfzaHE74JEd7AecRfqV3E2NCe3rk+MZhnF8E563XtF0UtwXKkXyRmCFQ3E9d+8/64XzdwtyO9zB+mKjOLcrT6eSKhwkj7uXKZWLzGHNRLqeJ+CfAdDlkN3KkZNOycxEzsyK7t3xMeH4+hjtN1WgFbU78vB1XsCnIGeA5xD9vQHSgef1INvi+NmVZgHa/+5EjubBqHb6znW/0XkJQC5UQPa2nAjksD/zLs9ixsTBuuMb2e2DbInMthyZBV0Esg8zhvhJd+fn9KhzPuKH79fYQ7r/Xn4R4t5oL5/ZClur1QT9RxE3Oul67rAeSxdpttUn4mo6JoFewAcTDZtl92PxcCa14pmCzwdL0N2rV/xlIV7lm2AzGJFxq2MuNsVpnoiHwb5qgi2ggA0yygzV8HvX9eLInjPB1gOdAOuLP7M3PpOp9++uTXPdXZSH372nsE5Yu5zMWnwV2SLAT940e2tX4UX77SWvHsfLgHZp0Q4H/gF+PDhIN+tgh+pE/Ft7JQR5CTqEvO7lRPbNFR3pKQW2eDUCGjiztvSh3XerC+73Rx+DbCeA91qyP1uBPLg/j5MB8g0ykEHpDNZmTegE5urpMKfru7QspyWhgW0gI52/AzngF2yefA6TiugbTHKzX9Iw//vWGA8iXWt6MJ8Y9EgA8izuUuhZ3AeaORPCANtnZHcD9HsSI7rMxhqcAX4BNhEBuhSt+8gfINPAvopnr2V/weY2Alkd4fKVl44/85tgi2jgL93N132cb3clg88Ee1SRns7PbDl70G3nn31g80iE3EJ+gHnVF/nPxMV8rMWIT3LarBDdxWQ6lrIbWgHvzlaaf6Zj8ey/sRMc3aOShz0jxNgaj+IbPsyUm/WBzILfmwtEc2N4pv0NnYgZ4XuwR1tjImdIpn0zN7mlV3VCqT7yE43DfGDM2z2Sb3lqBT7iV+P1VJsEf418Mh6SUXe00G9oAefzuNbhNzw4IuSMd57wYGaMubvxzDveBx6cgN4hyKe8B34DyJKveA+TCdEzWO6B95D8nQWWf8d75O05BVqtBo5eUb4YE2x8z/FkVinYx7CXoLPhfCGaBrP0jb4u6GaYE9irVWfGN2GvjD3s+1U3MFX4DNlwfGym9Cs/PpNOsvlkSwDdZRRTAJ8IxgyAlivgmYr01je6twlO/lHtXk8/rpPawVhwTgrvL9js8s/rPf7+xP4Gu/LHsfXA3z+33ankp2dhXyvPbBSIG+yt9mCP9IekGtf5B2CX5bpyi2T4bpp+pk9f+Fm5zhEYPpohWx14EGJMH+lgtM/6sHq0EXBkB1U3vQBkdnBjN53s04EPfJueztzZ/7eFsb81QUZYLX5nfeKXeVogE3pxfNDHtIN8ReOVbbpCdp7z3HZksNxW7apOkT8ypI8RfcxX50dFPl5B7q9kX68c5cn8SfxAvh3/Ax+JS9/4SF/6YBe/ArvxPe7Wmvuh8P672Aqyrxy0htNZfEGPov1PvZIRB3lSlBFXmnWDg6MHWvzCVs+fQ3Y++LIk2s+7mC3YUH7NyM+JVlxbDLYsBvoH/BqwgU7+jY7O1UR5Ea/kiAuNmIfYcGEc/vU4AdCwLVaRbW5Wfhjnh3e8ood05BGiKFtAFmQW30xOdgKyS8HWpj6wg+/X5vy4Nni/C/Hm4vzOZ2oL8bEg53nP+OQ9u9zOeL7OI78CX72JHx+K8gj4CGg+WORxImRLQLzDXC3t3NYMQN6PR+98T+wTeoI8hDiKH5t48/TZExmR4tisQsE+Dz6hwb3uuYsHcDfxkscxbng+RGOAzfGSd+TV+Yye1jnWMsgTAL2e50dARh6kG5/86NtML7L8qX1iSy6ZgPz0zz4P2h+YN4HOPfCIB3Jm+bNdCXkMQnQ6ILvAh0hlVo8lb5R0WcgNDJdX3dYGG2slR2c/96nNCGvpelomoPgtUYgpgp0D9p5nDF/Jevoi24qyy1wZkZ7v431M442PeJa5E5GA/JBftLMeYruP/HmQXs3halcWznUhd8Fc4/nvnu0GYE/Avuq3cbH7+NTtObnwz29kzY2MANvEcCCOjr2Te9ezDjo/4PFZW9lNA2TH3fDTRR6daLfN9/HZWODjAO9uJ8SdfLjJudhVKRi4vR9zcQ9ntBAX1j4aH60L7KHoGd2u44HdVhGBx5LLPoBcCsCnjFGs7lW+szvO8xMwF/3GLi0+ex/n+yw/lcfptxA7PNPjIKtUMdZxzoduwVZeTmHvkZ0K+5rbhy/jK20Zg33Enuw58ifA7jlUJ5XB/uhLFX528elfnymUvwHe2KIY1itaHP1B7sWZKvDUI6/iue56zXNHP/vW73/6c6vl4LOx8MyvwXo38bDX9ubruN3rNf/khwIfJJCHOfJierFJX9mskH+4ymdJzfPCh1tb7u79ZxlRiC0/5YPTXgPNMJBd57jGIy21ZgJ6AMXJDhbIrGPM6wPd/VwnYz/xDJqjScjpdEIf7euneQbqlIt74v+BvDbZ+5jnvfyUf+QvsIccC2KNT33MPxsDdBjEd/EmihGdc3zxgywCPQDyB/Jbg4UFsRDzxk9rXu2Itgh2AfilE8N/ft7zmPz+FNN8M47y8LNTLPHxc/A/gOdu8pHPfehTTDmPC0HMrq2dfdlX5wOtZ6UHXCgxiX3+1fWU6HlOPbcx8Fs7r0CbFu+iXAPo8IJMDbdThD+Z2Egnv88BFs9ZWzzL6OzWx7zIw9vP3+SU721x6ca/O+1XHmP3F/oNluVbWl1lnvRS5t3I4keMRuGMFWUR+IMoVwt51GseY+4CPgZ4b46e8/5C/uNJ3CH34Y7526Mu8W7mf5JBo0RUr2vK42R3YwKfRLl96eK+lfsUUgFfccu3OV8P6c957CZH4iOfaAc5xPu80MdzfbBDGAx/lts+y6Wu6hdpcpPHf8IbyQ/Yjev+VQZVkCHIvgAbz18+yedfYni9U+zh+DuH3Z2Z41m7+isY8AbIFRrshDyP/sPfr/mlo7yDtfjNPP/2aH9bV17Pimu92qmQAWt9hm15sNfuztULHXAT0+PhjFkohugZuR0n3OA04Pw59zr2FIME/JO/ys8ecYw3PZeJQvLW719dZU3O4xCnQr7/MWfNI3+gGMe6OfMIRwR64sp355jFjc160o3Fz1ooHgDvQdi5gr1/73/OYH8BD4hBvCDrevSDz3mZ6xtcIjobxbNjIF2Ux/zys/Ne3p/jYC9jR7e0vbHV8lif5epDO+lCDOzyyzOjV/nRIg8fffwBzBXFOmTA+1hF22eP8Acgc6q3Z/g+pnChM8hGEruPI5z8du/IX9U8n1iM1d7ZnsguWBl5HlaMOwy56xL+FsV1zLR5iX9CDgb48pBBnBBswGUxPnAZZwr2yV8YJwTb4e046LzD+v/GWKe80tvxwP/UkE38Dvfz4XgG+AE8juTBm/ESwCuAzpBe+haAV0IxMpDPWjpj7F3XbR7Hn0j7y3tATp7eA/KmuuqojzHtPM4B5x5hWl/Hmo7rQJgzM0jCrkvuj+NrWbdyjlFXFzAuxDlg3NXb8VDsLbrJQ/1ubTlWYgp+yhs6biHeArGWP90zHGJQvvdmHMBQCX+6HvSO13RDWMo7vM1v9ghiLSHooeM4yh/h3N7RLp/bPb0ueX2CB3/+xzz2u/ff4STycc40u/zsLCN+ztG/oR3xkH++pd1zHMmveOFMnyPeoZqAjo/uaWcAXv0DDMAntMvxCy9oFyMfE/Iz4Nvx59zXE+zMDz//GC/yCf2vY72YM/jcwOMnX/vvjHlz7u/HA5/C2J9i1H8+Vm4HUM95q3IcB+aDZPUpN/LnfGZBTBji2y/GpGE+g/3fWdvxXS/oeIyRpH+Fp0/vuj07ZxwRiq/e2NpQj2K1UGxAIYu2XtHmv40fXnwfsMUGkTWR7n26j7BGv92vGfjTkIO46oinuexzrhthGRvXGOSrGGLRvz3m1I+xx9/kym2so7ROscZWcwf1MzaK70Gdww58Z9hDKpyBf9od4ttZJUTYyzzHA/n9aN7SYmSfI12IcvwdqM0B+R2D7Z/pCN83Jm1USyQw9hZiqVuUt3j3fDfjIqj1AR//AH6i7B0xdwgHodidHPMsbqYTZZvPB3jmmN/CE4SLnwF+II9dIT/BXcZv1/L+2fx8FvL4u1z3tf/Y9jna8xiVzpkjrz/BDMBYDsQ1/3ys3Kb/cazcp/T+xngX2/6HMQ2U35jAvt7Uk/xqzKt9z70f8xgnbf65rXx6j8KK5Bu7MkO4xnucza9s2MrVzv9pzLNd/cdrBJmf18b9sI8nufane3i09X8YC/KD7p+uC73jBxrC3jo3MfPf+R1Hm//pWHd1PoDzelYj84WuzmlOSSv73gd5iqH+Q1saxRGuYz3Y0p9jPT/RmxfZVDjbD3b1Dcb4j2yQ3P4s7Nk9HT/EDX9CRwvy4dobOh4iiHf/iOX9GesLcnH8d2zO61jVN/OG+Aico7/pUx1ljPxmTH93sof/yngm4ezNN/x2HAv2poAN+Rv2b44RH70e99OagY/WeNRhr2laOea3/o4PcXzXk3N19vsidM7/hr/3KG9zGt7ndkFHymHRJytgIKJZIT8i3eBq7e3V7+CSF7mxbZ4HZlHurVq1CFTrO7rHmxxxJmBn6mAH6eN4m3/+Lr+n3vgqsM/+sSYe6n+NFsTr25ALAZs2z0G8zmWAfcCn1vN89z1NHvPJMCbUjxXqNcIiD+7nx/zFMb9xUzv6HEvw+L7zHI75nCLeKcc6XWhPFXMKJOSOXtSv3ud5xPc51Fts6Ft+AXwO8KyzOOEoL/r7Aatz/l5BVpzWDTZrEwM7IMea/uI5kMVH7MUXz17qQk+1ivHne4LeD1g+wKGBbrrHM3+9P0/wTvdzLt3zQw/kHtRdAD/LUA93eIeHS34/BvSGqCCcpwMyVnnERt3UQlNf8vURv1uoO30yPtifILNP78gxtR01gppvMYP8IPhzYOs84qle8if4WCDntVMu7p8/XgE/fMRQs+TlZye8SQ3qNLHODU0AC3G3t1/x9BhkL8hRA+YPeAfw46nNR+t8hiE85ealP5QDn6/7ht8+P48VoEtlcKk57ruX757wCxFgKJXwZn7Msga593/xvv5yfQV588ux/vLZzWvjo9ueNQW85BHzlwis8QRX9wLb8AYPel8DDO9A+DOEY9nNJxbkgcQP5SgdSsN3a7jTkd4POCPP+FhHTlnhTM/c10U5+jd1ADdx3BMW59pT5Q6X/XbPWnZ2psMxL4Zwj/SPWIsX2JFUWr3AZj6htcx8QetbHMMTWvNf0Hr0Da2xH2idfEFr4htaS5W3tD70Jp/S+jKXREfYEGRzt+xXWObkrkbunh7pe3qcefMbeYGwbw6q112Cz+w/sVVq55qv53hECTD3sLuE8JqWqx9o+QzzdMaGAYbODACr9KWeQ70opnkNOOBuwb+HmNnWuO15kJ5jYKj21WoX+hUBhhXWt0QYO/CvItQLCWHy9BvcpwU1PuDXQJ8G8AH9Yy1ALvu+pL+Rrw9qTJFdcL8HgG8Uz3FFhDnCCj0OHn0r0J2oZ9gRQ/ndHJCONt3P9SzwDOzj9rWeeeTl531dPqi1esLnla/5/GKHyI7Zzun5hQ0DccIA8r2ty7NP61NAZ1bkzHJ/rFd86ddZz84+NodY30+1Jm/skyjHnU6e1i7cYNsKZzLpvbQd3vUkox7wcLfvuvjaJ6zqDz2aPpOrkG9DeW3hw94uH+NUi/LveU3a0/5rH57/nK7xi7pU6hYrfuGx255sH/Seqxie/REm/QObIbPGws9npi3jT3odnnVBRR6O3p3rL3n7hIXOcTj3cvPSPwdodu5f9kEs5g/6JkIMDbCno62Z405RXBP1f8Qv/Z0+tZVPfApnBfbzGHdDfJz3L4Rn0Ocf9wb48Ay9o989zvyXMa73vQcLmFvyUpP9iJslnuG+H/tAaT7qe2ion/Si/Ln34Su7BWoj0h47qkiqkr2xC1Cfy1Os9Yq/Rf0ZEJbYSi81fYBd9isoF1eY96velXd1f0WesmvXfnTfnCVUF6gtnmHyirU4sA+53vpR/p/lEOqNAWuavq5Ju9gFJ/w2spP9Z/0vXuiSAk6G+oP9fPKdx7188p5n5/lxzffxdKAhOu+R9Zv4DfMCq47qI25qxJ/vTaHG7iwbkb3tmKsvfarbuMYnc8TenO3kWe+ZM78hOyiPOSA/93v5dqz5h1oAY4zZnfT550/iMM/6B3xoH/MZ9GMBfaBtv4gRHnnaPz73Qh4Dr2lFfymG2rPtnT8DZ8u8np9j3GaLeHmGzsnpmdOeX88MwSf3Mva4lzj0QYY4nPrQu+4bWiB7anNjhz6va3q2vrMPeritkTzmiyDvBvuHZ7c1MCebdpXXmAbzIV7oT/v4vUK+7DbmgPBXBZ12O36u0wo9im5qVYt2Dfa0vmp8tE2LvP2D34N9fzaPshP2BXj6dY3l5ZyNc3oX612O9XdA+/s+p0ds2mXfHnqBFGh0lTMnX6h3W9f71/Th9zIhx4Hc4bve1Wyd+ZGDftN3vtDXOdnv/dfn8Rnntk/Or+T+fa+jtzr3yfPyjS/32Kvhb8SIn+ck/zz/+k+Z2yXv+aldfd3PwSlG/2jPFORwCmuKv41Bov7Yx1zb8x48T/Ttbfzu2XfHx3q1e0zv2eZ+8s43PZ0GP8Sa6a9qID+TkRB/azmL8zx/8CO39z3d7nRE8lo/UEVsxI3tc9fPvdBfEeKr3ggz1E/6svmBFOjYextZfIwxgQ6HNcRID6iwlzOo0VfHqD+eDHcSIPmIxuCzLiOyYLMj3GYqcFXfSoV4Bt+Dms6jffyneIY/jnme+81DLyF0v8M4KfT/Af8Lerze+i7/t/pqR3696O+b/PCvePFDXWK8xuzf9weEew/e8+Hgvz8f/lhn/X8p/53i4Y/3IHwSd/1Tm+nHeFGRXuTjeMX1L5/0h6BQfyd3Cj5hsZ877BHUd0BM4xT7BfwO9E22f0W31/bK7Rovnx/P7tV/eXGmL77Znf7NYzEtPjFRTDKPJQP+oC1/a9cArkIE/DL9zK75OVae2zM3eeQrLgzyPkbeBwJhWj7ABL7upX+xif4Jdt15/diU+SZPBv3v8/yj8j128y5GWqTnsRen8RdyxS9i18W867/PRzvRvHri5UsP9m9ovzv7MtBrAvbB/jrvh3oL5vor7203WD65j+Bv5bLO60X3TkVm3ptxcMExQY66Br5qeMaedaA2DWrWovxnX2GyznJoEH7UX/2u3+/354X+/D6QT3L7uU0HdeaoXwjzuq/JsZ/I79591tWPPZT/1Nc4Pj+pHPs/vXn//d1Dn/F8cH4/yNIibZ7ZxGd5+5v3EzjSm3ERU/Hc7j59T/3tOKf+2z+Oc+7T/d04F7xgSn+cx3qDcbjPVb3JEd/3Lir0GUey/dQTCfK4vgQ99g3127jftX+lWdG2yF560SP3FIcIn8blL/E9mJf8tufzV7b1T72UcNS3Hvm/l75a3r9VD93j0f+4DuOB/il+sm/u6HzTKzOPO0AdTnX5Rb7k8/jNl7IA6AZ2JcIfxL/Dy/5x3C6nfcGmoX6RFzM+xSh9pB9v/F3v3Vn+9H6dP8IQ/TvOyilOpv2WPyLobfjF90FWgK6badAHfNxcT4ef24eIdnDXwun+hs+fg/z1DvJZ4L+I3+D/0xz/D3WO+kc1S9Usl323Nsi/prbrCxlwliGAIUT1tvkZ+dIvTD/Flb65exTu2LSC3qe69lf4p8IenXqzfJnbvdTmIqyW+YUfc6kfRrJnQi9OedwvzogGugPqoSrQ962i/PK5wQVT+8Wa4Uzm9S6o7x+G1ma1uN+Pf7xvJfvdmdPONRlf+EnHXrioZy7SpfAZ5P6kXz0P9ir2rF/uJ89+vd/P5j38nt+gj0hy7DXwhWw8P+M3j/7M53t1iQdN8h4oECf+pn4svyP52L/oOx7jc18C5CzyBVAfmOgR4/tTzegvY+/f4H7Od3QhXhj+VnZQ/3yZgfroIJtjXPXy/Gxu236xj1CviTDwIDMgr4z6Qh9889O7lV7oxQLG61ns+Q/txx8xz3c9lo89NkEHpjex3Nu7c5EvAH+Wnvc0bkMNIuGj2Na3eaNzTwekQ5Mj7gnPfi/PT7UjX8gHGM9Fcgn1hLLONYAV6d8oF/+9vPV/CE9tEcbndE93XPALiv4DyoETU9T/BmKHv7SZjrYPf7SdzPSxzvf3vHh8/tk7X9ujf352ntR8FvGFX8u/F+fjsW42fawd/s4uQrlKVCN/1n+j4ryf/vw1PvIX/QiK+kwNazr0KQd7Pf7T/eh5kWOsvqtluqM5OseonqR2vuP+j3ky+8X6nunRX77nQeZd6X1bx3TEwYHvJVxxWyddA7GvY7/tx3767zBNT+Uf0uk68s1QzLb1cVzzLEPyOMaHmKrLvXmPuVE7j6kcY7WFXGnQJH++b/7PctbX+3+oJ3X94k0N1icy9vF+nPf4xdN9n5d7jr+xcV+v7Y9wJ5f76p7UXxXuH6X+PbGO8902SNYHH/cjKdwd9LHvd72P6NYX+erZJ3fNfMbvv+Tr/9Nyx+fz0Hdf3uv0fo8hx2qBTvg57vaR3Dr2R8ePcusTXXK53wb1i/tO3l32DsVqZtk/te/N6/t8Hmlwc0fRp/HMe9v68X7cj+h/HjunGejk1V/a1/N7l9apJ2yx7+8tXWnU19DrHN9vd4d5bjB6X0t+rvX9V8s7bYZqSfpDEey+xJ1c9rl5ujcq+fr5H/j5yd22v7HLf1HXfXkG+m3m2IFfxblQ3184k9/ESGSIxYinO+UHzh/GU5/etf0yZ/1T7dU/r579JzzXp73i/gru67Ma2/8xfJjfG/4FH2YIf4ti6vf3VL67t+1bWuQ9uWGvn/SH+bOeCP+Edf857vrHHgO3+L4nNaYPGL9ndah3GKmbOtT/Dufwbm+f3/fIET005z+JWRx71N36pEz8F/IRl16xeU0qsmEv/Vxz/VuM+/yJzHkc557HYVwM/Im/M97TvMB7Gj7mof5iH7zbnCrYLDysFc+/DzrMMaFGLo9RZpiLcAyAnUa2TOnHeODb+Sf/lPkBVhQ3hqJVjEW+yBkXY3zXntuv8dzf9ql8Ee/dor5GDoptAGYeau6hhuNUswt2ItwND/e3+Dc8+DxefOoVeNc/L3o270/uFf40tjjOe0hx2/z70MNCn0jnWuqmAHfPQ99qd6LdrfH48xyr1R0f3/cvWOu3+3RjT/5qnfle5jKuKQSAAYG6grv1vcgZFeXK8zz/G37Mvt/TmzE+Ok/P6JHLRPX5mbuLI+e2fVEevIrt/824+u0Yb89dgO6X/2mdz2Xfi/36S7LvizU8O0+v8kLv9NibPaD+aXx2oe27M3U+dx/Q/9Q79q536jL+Z56RN/x/5u9jD1Q2itFdlJfahWc9bQsYaPn7/op/Lss+l9kv8jz/Epl9zc1BbaLVuomnfeJnPPRyfOFvvLsf/cs+nbe1Ri9rQP5HxAk+wBv95TjOce/e1dzL32D3/3vvz1OMSEH23sXu3vSuzf4JvVpf8k7Brr/z3177TMU+cfl9PyD3UXz+5Z1CLMLajkhDdfze1S654JS7wSk3/PZ5rqqrvtO7yiYP6JnlmN82Gv+2L89TzG6leL895EII0HNw3yjwE8gxuDutjeLoRZ3+4r5ouMsY8ptwFxLkoyvK/X3taG2oD/dCX2lIVu+gp/i5pu3J/PLY/Qm/Q6Ma+vS2vvJ5jgHpAdAfeK73XPrtum8xaHc9uVuyf1cng84O4l9nVqyJGyMaHfyf+0dKB9lz4GcKVvCtb+gxQb7lC2zeqfayEHfK/75FORjgBZTTCdBddsYLOfaMdne4yWdzgfin/jwP3j7VckJ+Be6keU7//F64Az4b5/cM5/2a0T1lT/Ur4MYLfILkzfFerpX0tB/usV6Xqr96ppvLLvldv5hL/5FjT6ZnGIv7+8R/vJP8dU2L6kAPB8N7qk9UnYTnlvf6BOrmz/k6qFk9LHtv+9prN3c6Ftdv5rJMcy73/qHP4a7YT2pVZZZ2oO42fXVH+o28u4wB91Izhf2Au7FBXy0/qo0NBgGMd3g2np6NSFkVsg/HzD+3AnRXKg81xPQHdQ8a5BVHia4+6xtjLA3P8CX1IxpD/htqBImoaKv+1HvnxqY82+tv+8d/Mg/o1wZyKwGc4tlvuLvjY/nMV4vBr0SYmW3vXqe9pDfkJZH8X9E3d3c/74l2xdB8915qB8+Dje47t/dx3tLnmzmDfMZve5VdaJCe9+m2n/qTewJuxouoM16ig/rV5neUSGc9AHOUQb7gKNeyRP37jn5bFFotPO4iXMlt/62X50Qac6nECkQvpfYdlz7Gurj8jj7GSKl190sbt3in+DEu/sF5yXhH8qhU9iBOkYb2KTbKojsHFehj3nEbz85RkP/75BnoUYP85dTEjBXcMbW/7YtXtJ+pxArs+3sVj/HuYv62mHttQe+0FsirR3rRRzmhtc50e3q/+l/dkyIW7Cy/b/sdSIGUSRnohMd3yXlcAM7whcZn/U3c3I30S5pf7OeHOu6CLVOV1GWlNx7VBaaxFlrHuK6C7snl8NyXN5cQO+EiZH+CX49qZwe4+YS+x/uJ/hKvIToEqO/u6CkPQB0k6FneO9E0RP0KId9ZHbU0sPMMDWyU1AR/4I53X+/3t3u0Qv2rn9FTPu5PoL+m50pu3fHQKzsz1WFWEqG8e9dzfnyor4X3eLIjs6P378KQXykUebECsZ/nvfJ/6Fn/NU0DbneK1x3rTrMozLE97ic8JaUSwWGy+u5ciCs1f1+Bd4PjfV653EHYQvCxzNXyBc8d/323nsHtOS70fv8bZzlCNjy65zZG/WxRz5b5zzz0230vxqPhfubmdkJUoQfZ6O/I5GI874wvZGDMvJeU/5DT/O35+iJ2+OzOnWd79Sd3rcT/ontH4n/T3R/frO9SE/2re+KY5G/VYRdkyPLQU83qt/1YHnqGvu4FWzyXmNESSMTHf3xnya0cfqo/ftsfZf7azvkL4/wpD3ylF573fvvN/I/3k8S/uIsD5RXjfK7pb/qk/aI/F9zHiOTpsb/X+Z5BGvo1RhBzts95GIgZGxCbPP7sa7p+Iw/zu6Pey/WfxxY9ZFkY7Ns9vei9P7k35ZseBnpuJ517fr9YI4obFuoMP1rjV9gdqGOEM3KOjf2oyz61i/979qb7CzLsfzzG+jfj5nmyv6qDr7XxEA8dfNXT4ZLL0ppf2Z9/H3s5WOqec7UxA8i/YP5OOdlzU3TfBJzL+QjOJ6r1IDQaxcOUm3vm/o4vic76bCKDv6RhH77/d37GZY2Wesw1DT7V61UZ7hN97zuJqxHspYlwAFcfCuJ2Vh9qZhgDR/kOzbNa2kfxbClbYpI3CN77s9ZwOqGTvGb46ks961d0M87x/UKmqwr+w/v7qF6sGN+55iargB8ZAM+Tr/YL7RMhjaXkrf+09C95hdG5Xq4w3uu83Ku9OvO1krz3D+k81lDISRZp+ElO6O/Ed16fy8d41YlOd37/y7l2g/xzwhh+Q7cPxn2Y84cxtndzhbje9J8VY3i0SXw9EHD9NN+LrNNoH54htXPeAM70De//1ZzRt3N4iKUedFVIJO/Z2SrOO5/7f/3j//mPf3hxOTY3brT9Ty/+x//6j38IKMeD7hOEHreQd8/ri+D7kFutLqG+bafA/sFdqgzi88FK3M9GDopf7VHMqj+kj7hFpDsDA/bodD44lKeQN2oL4ZlzGyXs3PQM5dPzvdUCi9mCK6+gdg/VZV71WCF3DvXpNsLhTRmqCTkUiNfxJ94GHBxxzbFOx7rdaeWfgYzSXJhn2mGp+DwWxN78WWBBD1yYu4rZJx+5kGejrvNrXWroRAONCz1BgKf8IcTrHsZ4fP+1njD/RUeGS4UX+2bk32DuCt9rz/DBXr3YQc6FHsOxcv/O5vn5xZD2c6wv3K0kMA7g6+QQ6NqE3gGo1hHt3+LoAwqPawX/wUCYniXqD9isKOh7mJHOCFw4x7jRHuUYw6tP27zkzov7zqO7P60R1LRDjtDJba6HfT/2NnDyfn8u2s/BXoeeqCgO2g1QrynA+4xQvBFH/Q9CIYAz5QpR77Y3wun5qofwlSZ2jBP2h5QL58fJcZj53Xk86n2YPvDSuLpDcgH4N+/jjvBQCLMC2PsE4Q2Vs48K/Gsd57FD9U/I3huA3oN9BMyc7YIdTghuYa/RvVkBwt7ICF+ZqQEP9xzDGhkRy2nCn+7Iuc4H5pevA+xy2MNgwB7zqs4Scpz4cZwqsrcRxnCE6KkGyJ8903Z5R1voKw+YGwPZF7BnN/PPcyUP4xTXX6iBlX2Lh3M7hjjTBOiwgp5tp5xwp5jzPfIhDTgjNt+H1Dm/H/lfNmA79whnCrYo4osd0OqW578a5/hrhHLjEFNXCITrlMLznoHPFhfonEEMtDIr8k3hF9ixmIbuoB43ceDTAHT3OacbPj+X1Ckf/UBP4Fcc1dOf6VlY//LZ+W52GSpD+L+OensOF8PElhC2s/Bc/ln+95dnTUBnHfh81QFMjZEWaHZzFm1Xg1gt5OPQL0fI5ZcD+27aYiq5CCuO3oF+F1zTPvbgJN3rHCH3hHJwAWmfcNLv5sT+bk5yYU7K354TAzFEFmQaYLSq0KsdZMgYcFjBDR5YRTyj5fID5I4/gByfZKNfgNsD/11Behf1bgYdTq26KdgVKZIfx3f+pXnKSA6ivx9lh/3p/E4+HtTlQw77iKWjt+d3oXiGDvp6lr/z13PrAQ0l2Ds4awP+2N/15/mBbEc2zVZonTAtYOMgbJ+Vyz45tsZHWQF+MewHinXmWHEb5Bv4/MhPRvkRkBMobhFY2XGNg71FVFHvlGW3eMbbInxPS8FHuNolJ5xLUbaMCKihx1COmSdQnjqPHY2O87uRO8/5FTCSMopH2+jsT4NlvgcIHwPy9/q+39M5l/MK0QTcjXbk1WMvoCKtQVcZgCHhQT+D3kJ3fkKsNe+Bu7JShJ3X8viOc7mnpDCX+31C2EXE2/l4R/rKcB8fwpMARpX59TrUsw+K5ADgSHzrBi+U2yrIbloZEwWtAeYjS8jmAP151vFZhxHPPqYL+u5e9zx/HvSOQViwB7Z7waEWdA+KNZzwNgXZf6PHkJ9+tEkQrUHmP7FjcJQTQPifPrK/Whcb5qr71Vu7A/E06HKw7XJdA7YPui+JHhpji5+3qVBMnfmCP5hmuszl3vG8oloZM5zwh2zBKJGYJrZImKvCnuS25e27EW5XBjv1MsfoQa+dz4pXtOlOuKuLjXNvX+X44LyvHZqfmFLXeb46a3f6+vru5LS+wp62DQfk1nUMZMM8n8vdXmiA3xaRvZ6PCfMEe8ZEY68GQJcOot/qYE7aEtAP6Nk6rgdw2qsOonclAXvcBPvhhq75nqH4NtSj5Hs8R5gs2Nuj76GRxhjsj0rePx3mt7zpwZPHYxgHxei9o99yM0eYn+PrqXNZK+JtAXyS2UqDHjkPfH7yH9BcnJmkYRDzBzuvArELqPmBGpJAdOnjWHycToZVsJ+rK4hhozqZ5IWvcUPn6zrgvpMxYPzaQiihPTquH2HnIFZpI513HudQGCd6ZTN10us4kBvCdZQfcs90qUbIVpqjOuoWukdNDscZbRX8qDuezfkhM/7eev5V8/7VGSvgAotyigf54qM46WgC+DLm1seCNWPwPMSoFIh70G/fAb4siksOLMAhdNo3+uUi5+Fzuw93a3S9Edxt07A7rJC/F2ILNpLnPWQzswrqo5OePzv+HIM7WV/arsf7u7gTLo+5sSNyXheCoy81PGElBYS5dulzXOLBj72u20J7A/jz6tG3Wp6xf1c5B2cR6a5TvKDof17/fPXzHs7iVQcW/IHrn8E2KuiCKXoH9ziHh/26mUeeN831Ovr7mQYv9lIF3xTdIzaapQ7Kx8fIlj7nuR/1FnxnnCA+K/qY1z9zF9/7nb47Yk5Xp33kb+4KO+o6oDGy4+C7aE7AH7d8XZD3AcLlmkcZ+94XO84d8EgyxCcOMdgwSR6bQHXIT+SlTlzuPHjgl1Ms4UqnN2e2d2Oz2M4lZrKiUR+oY3816C/RRTWfKd1YQK0AnG/Ur6EJMYlH+dsygDehvytj38d0zrx1Y6sUaAW5dX537iOL1j4Y85kxAj+W53F9fL9nqN8J6B5WKtb0He2F8/7AHXuoP9bjHG/2O9/Do+y3774HtinYd2guUKfpzF+fs9P3SPvT8YBn3o6H3nPlpRe64dSPd3qMQ6J3P8i+wjtueRjsI/3yHNylrVJ39M3r6FJ0PxKaj5zdngELxRhQ/Ocqk5K8hi7vkwO9N4ZVqFE1w3ubA34WIT2VP9sqyM0bOVmMVSK++2YcqhAvzZ8tIZpP4dwje66w7hfn5hX/3sriV/HKAj8vLcSfjIPmh/Y7n0NnSCEfD87BMc57955H2YPewSE9DDHZY66gYJchHX3iGaSf2iL0q5Ojo4xxYPyHWC3UPAxGaB6oNqoDNY7w5xxLV9zvwp41X8XNrvuY2MdaOhH8wyT6UY5j1/hn0V5+Ls/O8fET1vwu7gfx66sua8sM5HILsUnbPeHfcywixADdjhYnE/X5uy+6GMY4f9YNmoEBcfEnOu74bHuwnTH3cd4nevbuubOML445uvusKLNP8c+C/43Ow72dQUEcAuxuiDk8sQuO417ugkJyk0vudFUul279vdP6n+jAaWHuBXtvD9l8xGPCqVbsbg0wN8LPMSgnOXhz/uCMyAj3AxhWkO02xD8NdBfWERfJYJcx8zPECnGhl/mdrYs97OvdWrMLP1bQmPZV79/vOaLrPa2vtCjaJ+e5R+jsgS8VISwJ+Nj3Y0VdJu/TeMKuvbAjOWsPNoB8zpF0bnI2D37lZc/enhFOrEKuBezPC24jj0Xe5G7ufe/XtuJt7gryMQYBvRuhf+MV65LHEYt5njt9l8dJUM3Tqa9l9ZjfYaAfxTEP9UJGP+TJ8v1Dz76Vy/xVrl5t4Jt4yAfx8lexFMotYMnde33025zAcd4iunOKME7yDe7jPMtQlBfIrliP5zmBPNau3sbfTzZB9KON8TxOWMDiW9CvA/XHUy5xTVj/DumsOeSqhbyvXv4dZDf6CB9yG9fEvou/wbnI83gpiqmiuQmP/tXkYivQcO4gHprn2lsIdz8856GHr32fx3zguU/s+dnqg12d2xsMf56TvWhDjgji6RDTgB5EVYjjDWiI8wJ+CbAerdEbHy/vGfLKRkZyBcWNT+cF6Z6XY8A5d0DW6u79mRaQjkB8d7JBXsbPkE0OPUme7NWdHfHejptdc+W7KbzbOOZGb+ZQGCM+1q4vH/3+1rHv09nGQDl/N5ja87g8m5rL/4xWNkr7uxrdG8BXWnZIwT/ycORwIxv+RKP/UTpD6fAba1tZhUQfUBN5OMAEahOTZk2Bv/dFccDxoyGFezpt80oacq4brVtLRuc5M+PWsW70mTL8s7Hnm3LsMVlrP8RkLXEGbkOV9LXCjq2lEYYOvmIUQhk07VaVXOD7jAkEk9Z6LJ6IHdZcbCgi1L2txEydoIcrwjIh2vSQFpohBMJEyxWHy9GS0JmgJY2IgE6H3TKZwhWYXLMyxjahKi5HYaY35aQsuQ6FT4lmmJVbA9u0VU9Jt7Nddc95Tq3pjrCtwHZiXuAqo9germjLjuPZoLJrt90G0xouhO6EWg26Ns2Ngc1Xi6o0GibO1G51xXK52dO52Kxbc6vXVkN55PY4hu1QEeXErE2PVwy5r+G+PGyxg9KorSZAZ3ZKOiVjs96smzmNOZ9Xl0OApjHM3bb9v8Thx51j83ckx52jJ9Q+aD/dOZPOd25KTbZ+E+8kGTWy2/2xPdtj1nwz3apewlp6u2GG3URf9vjRoNFuLvsQz68K/ZCabPatFdeyPXYWqU1xueRocWr11Hq2jYhQUTQ8aU0ow6R99LuOGXM2ra3WHac2S0p1Zr7ZUcLK52tKEohZoyuUmulyeMCb00HbbtCpPhwNSpIcbStNM9rXpuv6Ou4cepKZ7Ep7qnyoUa1SwzPDqUbpG7vUYCdsUq60iagu7Nsj17Aph/R9ytVtSIHpdKe01emoxOuMHFMVfkPx+6hFqQsGp8cpu0k1W6gcfHskkovumm3sQ4wr1zZzT2gtywBm2iR7fmoPDy1ltjbZLlkmMLpCbzi/O9qW2WbqNfUSsz4Ys27PH09L5Xo3S514ul3L09jANJIiN3wpWQqpIiaBV41HQdlsmvVeDYttbuBzkTocqkzHG3kjzqGhno1lvMa8W59stBp8xju0qIi6PxnFGLehxXADc28J+mElEUallqzM+nBos/QQUjU2zUwtpj0YL6llotaqS4LTu5NhD14L2TBlsWqUDRxbdWu1gaQwA1qK1yV1FS6jVuzQna3qbq1ekx4Qi5JUM6drQlNDZi/3WVcnuspQJ8jyvA9to3iBrrap0oGaKOc9nva6dr+sKso0KBNynRvlbDccab1Bp8rogvBfBW4O5pY7/f/Mqe//NVGkbU+iqLL1O3iPwriRo8YcDpH+KaexDUrhdhT4A+kopMVNwvQVZ04B34Zdhx5Q5FCMlKHBhIzfYUONKMX1YNbtSnVnQQz65mrSq8iVKjTRWqnbrSzq64Y9djvtNbXtGFJpOWqU29vJXhqWZLiFcrFTfWZZaVJOiZhHODnb9cYHTXA02LdtnavOIivdLrWSPVl06wduJW+rbrsaEhtHT3qbkbVwO72Zmrgb38i225Euz9tdj9bmoSXMDZqUkkpcDbN5iOOZJskE3ZvbksWK/RFnMuRhp8x2+yStOHZF0PpLYWq0SpGgsykVTFrjamOJ0yVtFkgau+TVEK/GyazBdReSlE0kSWv3lKbKsm3K0QbUfNlD3YS2E2YeLVsZRmlmsxsM+xpfWesjv23qcBnkqOvSkxQAzytjsBhNxhtnwG4OfpNi91oQOyOjPDEHNMQv29Kk4uql/lIsVRwskly9kY36upWw/U1lNtj1s81SPSz3zXqyb1BSi5g1ND+Jef6NWLwy0t8Ujjv/IhyDLr7hR9zosJBGoN8YStWmB1sZKcMDx3CtZKQyeGvZjrt6h1dNGiOgqUvUnYwWKTvmXXG94cdS0DJ9Ptb7ZYZ1S96urxq2ae3mzWpp3eAXM0afL6SV3szqlbguZVtWITG8NbZTrDW0fWclxEEy3VOjw7TUMzcBSDBzuKeb+tygmG0c+4Nm0l80vU4ZV0qV8ZrYa9Gcm4UrqeGtXBA08w3mgfzxbY85VNh2uyuumH1jrGB8zKzXqq03xLG96QklsuGHXYGeRIHQIFslJg7DlcfMvVih54GwSfiKE+/9fmvZ5HVKasqHsUq1E8Pnh5axnRnImZ0yJWbQMRym2qbnVuPQ6JV4D7DOpBuw222Hj6w6yS1Abvv8gk57lBYkIldRW45a4naLkKg1mlO87atMl2JW3KrktIOwq0H2lS579nol7cBo4CvzSAMTj7dttsSW+Y447/T5REm0WgOzcJ6l+ubWZRYJQXdNw1S5WTycbymaMw59EO+6ZTvmlulUmmFTa6mWPYsHfXuXaAe51uJqvuSUQxBw7XWzFLviYMnEzXDkr5V6zJcm0AFjOm81hj2bbNIUE5WoEh/hs73mpn2izbOBUon7tWEsEGGJEgh60wCAWJOOEiwtD7Byi7G8aLUwl+2SNFDnDazRo4ge+GR2pVL1JInbkh1jYXi18WiRZIo0H0yC1BgElkvik1SaOAPQswRbyirJdLUZ1LPWcrH0bbs589QeXV7WS2rguLMJ3DPQ7sdkf7kid8HYsEaj5paZ9RYDt1RaL3fjUa3XwOhycx+SJeAzoX3obKk2TvUSqDc22ENnLRN8qztrlVQiGXIOI+5xm5g2md0oPWwgztz3+WxWM40ds024nb+TCbVnjleVcTeJ3Nlo24yMeT1S8RogPGJ7Pa0k1nI3sWZJLTE4CwODoxeb3Yq/C3okJmNehwrbYadXX3C4igNaCOcbNX7SJUKmxsatLJ6O5pDGrDlcpNQ4Ihzj5N5tcviYx9262ou8sjalWrtJNAEsVI2lSLph4bZGViv9Tjlh3CyddTJQoj1atCU8bdD7nsjAWdXLFT/+QFGFq+3U3P49sxm/6KplhnUSj9KdNUbWdnUFG2lJ3ZlA+76VV2OXtV5fFwCnS9LLBa1qGUdl3qiaEouWsp5iEPkpSSK736n12bSzxf1G2VRksEEMJZECZTWr+nN6zDDNoR+X7YCXWxhmb0aq5I7dnbsPBXc3mHTVdF3tNfrL6baN0fGiptD+drPc7pelqGtmDlkiMkPf9LxV219m44HU3G6rbNo29ljA7pq10XKDhYeqwpZpSU9sryoYTY8Fv1dcOgc9wSYO29aVTqwFChBhJXXljt80/IxhhYUiEepaVbPW0FzP5qKtWIoRsXh1bkMxFmX1Vb52sNR0sNWZijvGaysIw2LDCjNjGODtQVUtR5U6y1oJTS4MscsvuNKg8fF+/k2V4YhXe7q+7eTmh48NhodRVxgNuqNphxd4Nxp3xhW1p6lR35SxnbId+XbHDjuToUPHVLi2xm4QBvxUrCSlLtuTesS43cb1UbUhtg2JWPRmY5PYEbI3Ggtt3bbg+j/0u8lYAUW2Ybl0OUyGMq/vtmMqNDs1YeOLNUlY7bhBFkdLqVUnbDkdcYcqPTH627LrUoZlaZOdPanzgV4dj/d9orkPKA3rTt3ldEjMO+CMNYMhJbZHVRW6zsSVQT1KmJqrN3faYokP53FHx1aCDxmDncP4TZ/Ao/mmOwibnVHgxuRgGw0j+2BuVyucrCzlcm1ruVR3t5mLxKa1z7ColuHVNVHVoe6wOiofuNE8TPf+tu1zfK/KWIuyoNExr/W3WuK6buA2s6pd92a+mllWGAsh2exFNEmwEYghI1NbdSjJyGhhaVdoQ6zMBaG+E7TujnOHg+66zBniLmHrerfSC81wP06Xc2/LhAIeDlSGqcDhSnFlRc+dal8ZjxckVrKC/rjh7EySYjfWYU5R5b6vDhW63JjEXBXMJrkvCbNhy7DbkeGwM/h9qNtDvKrUV2Ir2wjBfqIs92DoLBmt3elbNtx5HB38tbqJxv0u35ZorVTulw4HLN4ni9DprZTEbdiTdDra7U2Kaux9f06QY6vnJEpEVPj5aqwv1tv2yuaq5a4RJF3S3JlTrHmo1A/2/jCYT2c6TtdxvE+1THW3lHtJJKw6FZLXFW5ZF/WpWGAgK+1lFN8cbqZxXN5VmemPJtfC9ed/TR52jKvtLseyzVDSwORIx5aq7rTurLmppRBJOYiYFuNii3WXE0lLq7ME4WYrOEa27XkU3uo6htqYM7VqlHrzDOMOjDmtdLEdtYNIQdKi+TXDtiiQYuCPczuxujlwlHGosZUmB/T0ZKNW38xHYB5FO3sQioSo63hvhFH6rrGF/Y6SvqiMFvJE6E5b3W19EW6HezJkIaa3UqNmh5/PF6v1wJCXgqLMpmx1Q4+a/XKDOSxVL0vbgrANf5ZNiLB/UzBpV8EESSika6RKrKgldnZgVxG3KXVY0ms17KWprNiaIONsgJNzSVJnw81ytREEgNWpM7GZSZUp39YlSoP/pnQUrMYu03MH8bDXt7aKafcVLXQm3V40X3jhcNrOQtlY1AJdh3Lt2pKjyiNsOKejqLkja0HfqFutOr6eDCiB8cLG3B0pXJOzl2KHZgWPo+eQGGEkd5hyA8pbDlqUTwIr1pqeGy3q/ErZOx12s5RR3G7ZL1X80mZCoSxdIxM0nauKidNe473EkihxuZjWjbbk+v3+BDfH7HBebUynUqNEd5XDQB5VKL+dMsPhDO4VdgfRKKFr3SWHeYRpMiXob8h41VlijikMdMsYprbjGwkNUdohZTRVd2jVNFlZNeUh1XBnPTat96tZMyH1MNxsek1i2oh5uQEWyfgwspWa1l/LAb4zxabGupVh31Iovr51G0o1GdRX7WF7XW8zZovBE8NtjsC3G3oJVY7lQTLvrRqa8+PBtKfB3zuYkn85mKMmHMyMkkR+0lZkoj0ww+VkCi1YtgRVjuK6G7VFG9sIIC99vbSIdw1atHiiWw3Blk8FgAX1hx2cVFp7J7WVhiksN/2KxwMPtYhaz9/MSX+2H21lnKlrlqO263D44+GaWKfjA7fRvcCU1moccUS7k3WRzpf9MNphakItxCA0NVytbf1wYoTDSaei2obNLcVRIgZNcXcYdzokvmsKTm8hCX6lNtIb26G5Ig6rAVENMnyz3lOt+mRFCgfwDXoLq94Pvag2mVMTfpCWDtG+v2fjZBqnqirIIR8niFgQQRtVuc1StG37v/7r6Ub8zYM8cwoHme9BxE6aDNpTeuEy7XF3supR42GbkndUp030Z3zL3GRrptL3jHgUmzW1Df7UfNIyq1UzmOLBNl4rzHpErZf5fz7ViajOilbDUqXGlkKjpgj4uOnSXIU1artss2MpeVFjGwm/UZv0urnFK1qdXM1Xw24dDmhtXqO7bSPrhDUaI8N+k1R2/XIPrJRV6Abqmp3se5ytH9Zlf4m1R+uyXO4rXiRZ+0NUsygGznGl6buRs8FpbF3R6VGqkZUDucjGCy5YeYFDllfyYdDqMPIuJTOHsNt8tE5qaHYLukViEMLACEyapDWfrDWqJYd1bL87ndqiWRVxambUS63mZmKPGkJnFlINwZnum+Z+UEs9V3Wq7q5EhuHOshtaVObbNsQfSsOQnffNWbwjm2KNRd8fjiE9RO8bkX6or3u7yWReSjLGawX2qDRYUHvJnx2iZRB3rV1zQHdBRrWWdjCaQWyp6c2jPUOkmLZpMntpZ4ae7xk9oTaaVGejpofXleZiGZcUZyGW8SrfNztj9rCexYtOV5fC+nJbo73Ek1qe34ijRokqD/FFPV6ACMKa4rg8mODtyDSjscv3DlylJBxasg7xeVrr0BpDaUP4z9YG9lTRSpTs2Ybqjvd+3PhRoPihOd264eqvCRUjOgsVy+/yHQrnlMFksVXqNETguN3MWGNjFxvM5G7Yb6idXqhpzKrMJX5J8eH1nYXE2hEYwE6HYZjOrlqq9+wya26bQTyB2Fe2SY1eeSFnoQFeVHUWrHVZovRuzAqhtq4fNsnIXgrUimO72tJfT9Z0uxH0hVE/obY20fWNnhhbyVIeh7tZWTDIrNoc9qbMVJWzdY3sxGUzBCzHtDcjO044XXY1pb9TzVmJk7hMXayFOOTE4SI5pCWlf5iTw81oRwD8pEabXm1rOlMr5IImgYfyBMqZzc0EW6z6s7CCGYs6uxD9rC1b6iHGNyrb7xvLjcoRYyHFDWwmH6rLSTdkIaC3j5g+WXHFGsl3lUYzbXfkrK+yk2W13FktM2guucK6C4OdtKJaXNMOu5Sf60YtCFRtzh9EYeQ0DOMAWau+hInbWcPzyqk7V3qJuAVh25zXRll2oNRdmZqlW3w6K3UnHSNRaqTc4zI/8ao4RFIs41DSwjk1W6z4kshCtqNBNYPQ3zk1Lu3W9pVAaa2M/ahzMGuteam74aqDNbQlDbnsMK/IAHFOuF7KzjC57DZna00a7p1eaO0abIOe0/1uQLUwesF/zKB/U9hWCxFAE+/6PEQAIxyQ9y3OD0dblkm4cd0TVF0Qp3C5dRrj1AKDOzoYabRrdwed0KGYzsDaidRwGpmzZDj0VH2XergGltB0sK51zEW4CPx5nFmVpFzdkJk96dukWllV2r25Warjlb0FmGA/Gq4kvrk3Ozwn9va4sm6acoWGSKReokJJXlKrBpfO+STk+eqhPClxB3dB9Zb2mvf2gwa9UgaQx1GtNS42qunuEKecEvbtEd4fEb518PgRjvlKg87I6nw1WvR7NtOOqMEhCIJGubXeTTTjIGC6vG9ty0K3xJW5zVTlKWGrSWa9sT3IvCWVy8nE9DYrztoeDgCqrsVT/6AEWERscV6sTLIRzykEY0wa9WV1hPl7X9kOJNzdmbuoMo4r3W0wmjsLf7nukdm8rzfLHJMynipKW9KaAcAFbqzg2sShJuj6yMUajDbXGjy1nlFbgGLjAVFW8Qk0hN2pnWavtBOjRsyUqrzFdIeh19d8sh9F20A/aGVmcuDlxGkOZ/5m67a1slUCJaTqWhiog1Fp3h9aJjNp9HS5mXZqdGVOrw/9QWPVDDqVIeYmdJXcjOsx0/SoXp1tBUqy4JdDYzJyt1LVEqe8EgyUg+TtSyXYYXIXm3ijtmhF6WHuTfio25vMYpnuk7HYx9XSUiMa2Qxo63l4Qhget44a6mGyS9dGFIp7mhkzRKfS6LRSr9cYN7gKs2AXXckIa52QxGOgXG/c8uquz5aTToMh2cVsbYltQuF1r0FrlQGjDGfKMJzsZ84EG9ZHaQKeY6+Dt6Y1olFZpUK1puojomkzrtXwyEHWXWq1HdgC7Mg+zImJQkH6HiJ99e3e3q4oiJnNBG4UHGTGq0tJIFUbbKJs9kxbq+48UrShmXiZmUKqKG4sq8xExQ+lbmqHB3VOjcmGm2wl0+9PqC7mzxQzmEuR7GYQR0ynvgjtGKAdjSl3G0Kbw8JpeTIpc5Y7lFZVj1X8eg0auGY2makDujzo1lZVU5h0d5Q/l8K0setWrQMTl8jVlJ3ZanW2GTieQdKlhnQYuY2ypWbylmTkpKrgreAwa1vgXVt2f9Cdma62krPt2LcHIrypSo4Pk0Wby+auCcUq03E2xpqZv6ZXra7dnU3WdWmwk+R9U9R6FW9jhYsSO0jakxFddjeq3gTEYd0zKKVcscUKyy9Co1H3Nkp3OGvUs+pOwn28Fe1GxqoSGPysVOn3Q9yr9pr9ib7ShzK9ICranhaxMbWa9ywCIqYyfggaOl3jZLjyZREpsy25j/ZOg2649sKJeq0DyTUtpeLpmrfJuK6HN1p4L7K2frDbJd3q1J419obc55RNZYN9YrgGu9g1/54LUYh1YhzyP5WBtj/w0gTOv9akF3NmmBHSbiNO1q1yh+bCOkS8IY1os6tMKQeLspp1lLC8a5tKL4jVql7XlyLjCyo/Sw/pcFhvJ/2UJTp8yrbEqbhp4NBAa1mX6u21Vi7bldG0DFhfcbynwiZB096BYhpVzF347qFZ8TKHUxuqmSSHSSKvqbVYnZO2sxZIZYKR83G9VgOLcBwvZK+398WtVWspsr2hDns760U84JUbGGn2NiU3shfgwGwCqI5oubvU4nvWJgNnVOwrkd9RMaLrUtWStkBk6oxXc3KeDRXp53hAvht/U7Xp0TVSiYH5lUGkchu7u13NDSmnZneildmTBoxLdmabtB9uxVpr1N6HnbpJcBNAfS3WJUgEsh2QXVk3AnHm05Nq2PBrw3K5pKqy2DuQYVWnajoFbYkxHlIbfDBeqL12MztYQwfv7dWN2JmDbd41JgdtRunJKPWqmc3zO1rvxdPaxhtgrDdPmiocPlOe8bswdduuFdr4kki603mdc+VlZ951Yge3Ibo/VarLmkSIzQVgqxbKPlu1512sp9r0vESpe4FqSxQf8aGzt4M9eO+bzshNRHlG49VeuTNu7bdrxSWxkbOOLZ1XWqRQlac6lumtHUG1VwKgNJkwYrq2spFrEPJRDsR+Y2vz4a6pTcdtarPh2uEwksgORyyXs3SQLg9gI3RUglc4dmntSFu2J8RobhAyS3AUl0lWcFj35hvJndWrq75XbhndTbsDOraXQFMaOqHaSn/dnx2EuBTWwCFVRWxP05zi1tKpmrZ4VXLCXlUlI7IEMos92JWyu6ermYwFg6y65+eqiTUEq84tEnabNBtKukt4roRXajOqNKV6C7bc7tt0yYeQfplT4Ls/M2PkhNvwt6Jht/Q5RRsI7pwYCQrJKMqBXzQ4hWZMANMQZEqHO+gwTodD1uH8hHVNym4xaWfTrunseEn0iEFFth17kolusJnuo2hUC2x6qTCM1amy1ZUPJdDcyvNXUksCOA/Nq3yLpJaBFWz20UJfs1OL7MZ8edTo+FGH8KZ7cxCvmyzvkuVDJrj1g9YZzCugKLlRier1hU1LKLFxYyXavhvqFGdOdgnTdvfbDMpKItvHofzNqwc9tjLbtmXV6KYiEzS4WmqBiW0DHsYtO80quMel2agUl7yx96Mxm1P498edXo5yIof2nADHf8OO6GGrjEOzF6rGkGvaqEjKjh5N6EGFJvDDIuEGqQkJAE0kt3uy47KALGVqw4NA1ILuWpDZPjkPMFFdErGy3DY2zVCWqrv5orxcxo5c7bbJMi+JsNVU1271okG/V00sSlhWvRF4WX0lnk4DqlTttVbrYU2a6pZWO+hdL1VLZXYoAMJntG0TNLseamEkAARyJ411fBMAvkVuku4M4znD33tCYM0ggblIhD1Jhw+/lgDt68OZHhP0Agt7y+mupep+/dCU9ovenhpvVqOqMmlic4ljxg2mF6lkX5YW417VHtujCYR8Wt1FlVUw0jHqh4puMrhCjavteVSjar7XH5kHkC8bcBl39LLqloJqu9bd00BohjTdcUKXFVVxMDZtsBu21Gq3RX0bUzOsK7RrEO9iwMdeKAwAaERwujVfhBQZMWo2tF6Ki0RVKDkHzk0qUsNXnUl5x/nr4SwSdjhfhiJ5WatTstobj/3FIGlWMEg5VLHRck2IdQDf8HS86iy0vjdpZ950uVsPAXQaR/UuBFL6G30w7R9KPUPZkDSWCQcdn0ht+YN8Z+yE0V8zAEAhFDCCY5JtrKedYS3CWblcbozT3tzZufBGkmu1sWnm0dlOGKttachndi8BcUlWJ61WIwjpXt+G1LMbzZ2RO1QgJaP0k+EaYqdDZa0ymjKifY1sYXam1wDiRbXWU7K97umQkU51RpNs7tCFxKLbVSK2RSrtCbwDdP6WNJWEI6gp6/IdtwW2/XIJ0d4aXI6ET6scHy+6dBDZcOHUaiRU5jtaYauLMVViGko5Gbiilq0hBcXKM4WVZi27XYudHTWkow0USk4wV+2DKd6Vpi7rHwJdg/SP69At2JEhI6/8eVJzeZFreeFkavMzCD8fOh2d02N9LbkkfRhMDsy0rZLJgJFZ35wsy+2prRjSUqFBOjZs1h3gLBgI8ezQ2bAYBNlLFCPoc2rg2J0QiEArkzFJ2swksJQBXV9L2yXPtceLYTpQKImYsWufcaCI9DOm+Jt2yPaKQAzYZqhxnHJYyYMyJ49Y1lgr4Xokh2s+GtvemPIJPWg5Y9kWZW/acQCw5687mksp3WQUueLU5VcDqquMVG5J28IwFMLput2qkHodqihnldmiXFkFg23Gmtkuk5oVIqvXiaYFBbe4cAjoamiNAUgFFzqT8XBKpB28bM0nNkAgB5jJemD2UbVxGRSp6dDDLjk3Na1mLdI56faGAZ5Wok5v1Z13o2AStxv11XhdGTsCXiZoHZOUjbRQy95418zK8J2s6VO7EgOQRrbfMLbiQj60kqYzUwVyNhwz9AD8dZ9QpT7BzKh4W8dSu7RRmDI5L4eAo+/b7Zgq1fqkGugOVdfpAJ/bWl2k2qaW1MT+XlTbK2Xeo2oKxpo+uInCsBypZtZXunPJ1JyK1I/cDpCIbseAJxyRpCikxprZDap1uORLbvLceM2QrYYouGOJXaz78nDRZnud+WFRam+HsZjglFB1J4fJYDy2aJISyXGd551JXI/ZZMeCGePubKu8CUm/V41r68Zabfc79XnW6+wUek/t62vF6UdSh5XIalOruJMRAGNqLlOPIPhJD7TpMmaqYZ2VzExzh0NsYgfUUEqaRnsuSxsIC3YTfzQj5SW/jedDfDqA+Am+nx24nl82Z31Ng8wuEYQxNyS3C7ovk5s2ZGZaJalilKmFM2xY9Rolw31s/YVsgeuGqWSwSJrlOHVKYY/rVvRyJDesAeUuhqICuw57Y6zEwSrlLLVyiFy/pgG0crHWk22b9aotbpZw9ZZNWjwZiHhH2UbOjOSCedRer+16iOH8/9/amzU5qi3Zuj+IB9E3j/Q9AoRA8EYvQKIXndn979dz76raVfccq7vOqZXLLFZkWEZmRDA1p0/3Mb5xCnlAQwvOVWdieW67zl+NS8tu7EUwi0LLg2d4ZtfulzrOopsF7rUAVSxoacyvZPrnJO5pn+73icTaL9Oq3gswIVAWcoo8r93S30vsKZPSK/dRGlEuQx26vyb6yX9hDDK/j9fpm96nYLrp9UFYmWSfKOs82pOpvubmhoiT5KVLkh/mGjwsTy8aQTZvHqGDTPkLehOtXksVlR3ENB3VWLvNdoHwC6HBT1zWfk+a/wvXyq0pyv/r2nH5T7Xj7hGizR/K6xxws9t4ezoeySAfsf6bEm+A4zTpntA1SkTGM259Y7gsU3ycGBHYLnv4mDnl2YWISnITjZ8UHfsWxS53YN2leH2/EnR03KRkL/cGpFXmRIIqHL6tQoZMxONW7j8UK4hUZjpHiquskDokr+F0VldlQsX0s1yS1vcg+OBq9tOrG3q/6p3gszYVIvBjsKPJ/6TmqwR8HpoilKEd8e5L7Y6R4+/o15vIEDzfwks1zpGWftR/9Sf7P6gZ4+4/asbY/mOoEASlP+S1kVcZNZaGEMccnFCnbOuCLKFPVC+y2DAQ827oSYsbBb5rQepT6Ds9EqK6ndjEfBpZrxte57tSF0X9lMFi1oCA0v08OW56lCfnP8TuVSt9rWUdw74IVHoikoVO3XDrUuSpzt9eIlnOv67WGh6dNXBjUGJK2vA0rY1wjokhWv0+LLTvUdO3dPnbSdQwJ5NA6Uwl1tzKl6jPDnz6Wu6tpyUkKxa1WCOIYF/vPb7xQyVYLGjPzqhDrGBNH31fHwo1cBGEuXG/4XgbJHaf3dhf1/fvJpP71LEUYKTGdjctcVc0kHKrqsdCGtKMXdZnrkHVs2zu+jFGvkoss7zeGDa4BBNNZNC/ouYmg+pVfPLun0I0NoLd5HlVfEK36NatOpN/cVp+fBcBlN+5X5ZfskenBa2NVWVQidiaSsIWKFrmh1nCu+NcKIzTw3zjIiQZzrN30N5VSecbUXcl1SKuX/E13VHJ/v/nxtvQ5H/f4Ngz/qPrE0ryve7gI4KHRqu1S9haxlpjtDR/7tGNFN5cXellAWKN8vyl+f0VB7UHFwl9V7LW+hG/ayFW6rDjIYrzFNT8DR8tPCm+EtKRFr5KQdq4SEYaLgIJEmLhewygNC02Ew+LWx/7cdbd3ptN/BK4stfuaKivbvnqBTHu3NjjP/lE24ovHCIVJ7oGSuWtCW68HAR9mMp41lez4puhXcSqy5dF9S4fw5CEgRssVONUfBtGuxvwpBn0xh7267Q6XTaoDd83p7rE469MOJk8wC81mb8Xc3f58SJ51VZfcDpyDYhmwbHCg6RBR49f8SBaqrjDN234QUCWBvtE8Oa2gZxT5rfXxvMg+qYn7Q/j/C9tDX+e6t9ZtXXUv6bQ8j90bp4T9j3/BtntoPcytIWnvZ2u72vnra/wxjSBZ947nPgq3xhybnYvWah+vqAT9RIQe30EU3wZHGgK/N8p+vRETx8qDG9VtzL6w5D3OrAFlP+5x4/30dqT91YWi/R8BfGadKnFm+CorN4WPRUhGrhtoJ45N7sr+YypbDMc/jmj74hORqDa63Jf3csH8+Wf8bqbPuEJVIoFWQsXKS42o+WwfSj5H72E3ysm7WPIisCWsX74XGPeWu3lnycjnEedORsYXw7jrgNJiNoDUan0fNAK+s5rm/waHjeDDXatTOTs5ormdyBjvGuzd5rJCxet90PJFavIh4qlH9xvvPjpNGKICguW4RbfdZD8IWC/TkYLw6yxKb9nneRdlhqrua1PHLoQ/eku5ojcsRDm3d3oBkbucMYdbbJ0YwQXdPnDekWeHdMhyFAo9PtrSLHDeJjy2cWzu+O3j+YGHQ/Q5fHxIQOtvFi0IocJrhAY4vuve3oLgXRzVz4tvZRQC2iZ0CuakjrU1yi93+PD9tnBijfHm/krn1KjWgyU2H1I2Ast2ICN3PodlFHzCg134UEPX3E5JV+5V/mvzVcRofs5RUcDQ6n1hNUex4vHTbURnsd5ieSfoUcdI4cMmoIOjzkrmMGV9Wfmadt8J0dKbZ0Ji2KJhA/ZMI5hj1Vxklr56uhuFa/XwGq6ueyfti8zqioFzQTgWW1BvAJvMnJbFeJWK1utbhxFPCD4aXVQntEtbYB+f8Bh6K9slduvpMFXfKxA24pPyWz2pZeF97ATcuwZb/4rixWug2IwvA98Vz9+8frfbLNLmf+ZUv7DrLD8bRttN/5ro7WxWYaKvsJZHE0xA5R+JvdtfvEWPp62Wj/FK60x9pWRBjFEE6ZhiRkU23OcYXj9mtHReXumOvPl7DQNxqC0+Zzelv5d844lsJV4fONMbrNeaq6NhsnZxuGEDdb4HzXavLrNt6rQXoD19xO3Jev4/RpnF/B0tjWN4eph9mdOmlqLIzolHHCKrLwX0LoXHOv2foeaIFW8NcnONi01bIUCsFun86uYn7Cngro0tw795gbrrsjn9B5FfG+r24CQswqWCdtgwVv8GUQJsYdez5qvScouC/q2Mvmtnby6sxX70sHoJDj84OJ0R15fOfQrgotPRwqLKQ9BcL6vJ1h/S/lxsQZIxEHGSTrXE9sEWrFhBC+Yj0G2q0S+I4OHRx/QuGTDEjOCQXUagXUdGB5IZ3pH/ZCCg8EmTrnmITT8zXNxlxfY+rrte4LtIKMF32MBzeuHOXJO7xLaem9ZzmCRbiPIYVPATUJ012AUtgHTHutLK+mZ4gzYUx0lK/vuczZmTRU4+/tSHQZJku8zpk/unZAfBcthBtxurFVt0HSmXm5yCT8pPet6UAW5xb76QXabfc9K0B7Q0WlszfPrqnAef18AsuzHZiP7+VY7gSKu25wEU0fcxC+ymKE8Vo9tdpeRb0llWNouz0Pgy2FPQkCoVYJXNqb4EhjbAjI9IslaqQKEuvUJ0snBQoaJ8BOdaWE0g2r3fEG1BJJCfhJO3msjqDxPfo1UptKktWksZ3s4wySBxNWDceT17UGX2DH8oHNrs7m2UM6P7M6bud52FwHRELOmC/QHJcUHqhu0Y8IQ/e86Gv/ltfg3Ho+C/Z+OxxAbXvLz2bcO4XHbM60duO2/g7XBnkzsDCadzCjM80GNQ6FQeEi3qfYF1g5S44tz+HMs+sIYAlaGa4vY6AoMwDmWVqGqhjDEQ0TnYziGYtLkGvARuJIVCFtsaHc5zJ24A+rlaxHzjoGoekHyb3UvkODTMx9CnToOE6bhehq48FhI/pschCbdjuGLMv3Ff7U2SGRHDq/+Y1VI1t0Tx/lVr5xSeYq1zEq+6++DUNRAteUB6I6e/cART65rtP52TIhk9go+toO3NS2YWWf5fIkjZbaoWGIokqBMcUPQnzNTkLis/YxhjMazeLiC0rYtNV2oMfDHr9gbeVPmsb1A4s9bH0r9MUoFy4eVY17S6LCqhKbEnvacvZI8tOi1BRf8kBsqa8M8IcMGWX9ze0jK4LJ5L23aTB5/PGz+JQguspCgDVeNxz0W4XPN93tWwS4+FQrmVZrKwwYGLz4dxsI6QmCcSj/vtzt4g/ZRZKrgMyGy+Hry4mI01fppm4LqYfIQfqIHS61THVxS5/TpC1XvAX2fh55wnIsRkY9Igu0J5SFtJSNfdSlO68opRNNsdwkNmxf/wPcPD8oX0NS4vPk7lJv1AI0fa1daipr9M2TGotMu6PRkwIYBEa7Cu4r0zinXtFFkkdzyez0+uRGBmQYDmhMOlfbolzHfIjEdgFzeW1Pr/eUF1farclDeiZfeLoT/ME0kpeJtvEErXsNbAZXvd1LPaMvguID5kD0u7ObHoT3R66ukOJGswl5RCLtIBBXZM110KjHl10dmvrcai5iSsqG4h8Ub1dsnq6En7pW0dD5Flo30F7P0CQ6eOJBcUPfXzvCU2w79bXG1aRbWVDEWDg1g7k5TiEXC0PQrUn6xe8OuTNCtWLTol3ptofv6ylaNT/hF555gsBYwPfSlZ3hWYIKtHwFPEz7l/uYinFNiASGuNIvOCMIlEvdVfLaFX8XsPPgnBwymecE7y+GYRF4tGd2x6DVwGxZctwPXPFSdI455UZ1C8lXMoWqUgjYs+vAYrYgEa2Fkjd78khmW3JsB6u123o7ziw/1RO/Z6fVTBNBYgcOBJbkfcYFKcTUfKIGRSPjUdL6YGOQCKVV7DVHhbfZ5HCq4k36u/8OtjE3JIWe9F8A/vOny9tJFSpA60MJxc7cG+5LtYinlyrK5FReULL3x+Wi3E7Q1ZE9VEnIMDqOOLFNpVFO4/jYD3EFwj2a7Bmimut0bQC2Vfyk3Og+fur2AfgQ5+VfrZc2dP5gKpB2oncKoupl586iW6wdbPvFI+KH8Fe+XDe7M7/UtB/lW0D/WNSTSvJbTG5iiw51vxQbRGfT4/tbr903DL+nramtpYHQkID3DK3pysB0cVtf9JavCzTCI7CusN3X0ZwpOxbD43BLtjthx8usOIROb+8yjL00FvUeUigG3V6RHuntncdzoY8Y8yL02v7fRezpgKSQsZx2lV4gtyy/+HTe5ooVCmJez7TuN+jDgUvST/Q3Ovflu3WEG+1bWq1w9pxOfNsncf7b2NOVHZ3Cv3/ryGhgW7Vom/4AmMVikA88vR23MZKgicnleKbQ3WTrEAsKelM1xMH1uN8tKY4SDKQ+wbNa1CfeEenph8nC+MKReJr/J4akuxi+XoZcPye4qGh4KZ44vU3F+kOfDj/jMOVwMGuawej3VqQWpuaept/rFrqStPJuRCf/7e+B/HHXvdP37yk4n/C/gB0E2eTmEIsHSafAa3bw/yIf9FM+7JS+A+FELEnjn+pObS8IagjGO9WOXPOU9uGh9oKrDu0kgJJ20XB/5GrPn64RCNK5+tMgi7c2WjJoOhRvvmxAJgY08TIm1Gq9laFSZwZBRKyM21igKZMpqrcwu0OZXJP20Ww3xMHhFk+7tttE/oRkbX/EtS1inQwq7NaxX/t3aB3S9uBsFzqPZaLzvob7724YE79hpzHnHB0GGRJMY45gHJMl4vZXAeeFkWq0V3qXliu/7T1R6/8SBNzGoFKT5JcnfxJfayvvrz+Zv1Xj8p9kKLFG4pdsHdac/FDTUfkbA3Q2f1XvWawBbnj+jjZZAgk/KbEFLDCIk2QkvmQvG59ExHqO83E+ni9Vv9o2CG1wPz/eJ89bDqQUdRKK8NfxuPRJDZ8dX7ghSBx6XQI9nQBSwCZMUvpIloSGm83xJr9OoTrFpYSDhv3c/vdLDpL7eEWgUfteLQX+qzv4S2Xc/iFe/vomvPCbrF4WN6XI4YEmHR4ePA9kvvQemjF+YYpVdFSN3Cj2dP25fUo3bSrt/+eIpmLsc6mJoFpnAefrHg6YROvF0H8y1ML2XQYAp78frI7J4is5T2VpC86UKeqnCPWeuuZw4eiIyiAOOnj6UGmvLo5HIvvzs42Zcne1JmG2et3X9p+7KYfqtOjloN4zW+zWWSRCdg40GPcEzZAv6zXvWqgwS2gXCIpzbKYr10rtx6kBFYYNGtv3ccCjRiRr/UVf3XFScZP+oM+7Rd2uU8SM0Zjy4zihOiMhLZrzdsKc0kTPRVhCBfM6oljm2rvJyG/OPGDwRSK3cXj37oQz+ry3Bf1oi/74dIvuXpyu0QKX8lb2NXV30qXqp2OxzoEzpuYB3QbX1e12l+i7bT3VoT96biovhSSN98cYh0+Zn9t4p/h0HEDoKwLN5QUcO+gW3CzTtP/HNEQzCMLcX0xMZqtnu1/ntLgm+8kfU5RmBxfe6gEdWq+DgAczZt+eYP/mzgnQmK0aD32js9l1wb+h7LfeP/Y3EXjvHTS5KSQ9YlrDI10dput4Vv5Li8tmyBtbeY/ngv9AWGgJ9DL59k+NdsFafLC8ZnvZbfwMHJgTtg5rvogLBbp7zicsXXaT1pl0eVE+2ZTa3TnetoP5es/4zSy2H/EkdxC6SnkNwB8jfO0wJ2CDzZPjScNy7AuVxv3ncwwwwfpRDCseNvIgsX/Jm7CE1wsFz7H6YjQktNWR8redQCOCj2jx9pcndCDkcxPe7wrBi322f4BZJ6uHD+Nx8uGstpQ563UVSqCpT5R9i9GF54NWUdA+yeSd6x6v8kF3tViN+2Mr8CGCpqHDFKdN3ATrkIgUimoDwnmDA+xzzC7p2boUoc3LM1497bRPWfZE67iwlf96R+3J1JNSy0AI6GIxHCZCOL82G6LjSBu12BHE8gkVEQUm+qD5mbono+Qz2/6Ol/HduqMy/9OAhAIJCRY7dDSno0xUEUG8kJd50ojimSviIJ5WJ1qYBTcFsmtbhlBN555feeb1yDpy7QDwzo/UBLjK/nmNL1E1/CPe40dOv1yJMjt4QNxhxCob098vCDTJDa5YCad2LuLlVmb/YjD0QhCd29cYTpOZAMsKubuccYmx7vG6ln0LXIbeLj4DEd/MCjX2i5g3jvJpku5Xn+M2hwK+ohQQfka6WMqrHYP6Bl/T9UM+nkrQubdFgMllDyhsk/jqPuD0UcvZg1OuazeoIC3ho5OVj0zrwkKicmes0J/VuOPKBypMil1P7FqxdB/IDW4jNIhnUer49wk54g+CfDb0ZPFw+WHXFBG4Kuqushad/dcGhVvJ9TflnY1bhGhGzLJeCm5EHAHSL2fZUI0MWP/3s2KwavDSulF3zjZu9Q5c3bKTXjW2hYzzK5t+Zeq45BEJqqyicYveLLaDLszypW5+FM9+Oym2K3HQ30EfegaE3dfWbkX5GFE/oa5nOH2N0PDEr+wIqY7OaxSzxCWMU79msVSDITgq8eo7+3REIK/7d5g/Ms6LCadCCrLKun6r7geSrYHEs/5bJ3xgm2no9hWxK+zMncsg45LAX6BqLl0lbD3VP8uaW4S9FSpZVpQjwrrVqDHISDhUpewP5OD3ebGuU3An/mkdknci8ZWXXYDvD2kILBy/gFnHc7ec7n2NlIGtyQH30kKjNGcE0aI6rGiDQ+4zvTuJ59l8qsrw7HuvFYcHM/8wK8wllL6uYMni9r9jkzVyLDbAUuO+Zf3V3AYkmjz2/BFgpv6hjGRP52IO6A1mGgoYPiu/snbTBOBU7ZEX/Xu29fOlO08ZoTNxoRt+vxcbwPP1yXh4fEaW+t5V+fhl8lZQB00hpf0mu880cAs12/7I/oMhwCbEU9il7g0/y1QdHKiijSPpTtj/d3Opvzh3UlRB3rTM6+ibNpwMWMl71WbO1TaMZ5obBHxVMZUCz773Mn2sTX1QfuEHN/dpi2Orwrt4kwSTmjDV5L7xKTV9kIXMqzLbfLHDk9nCRNzTygcQQMzKNvKpz2BgO0hiVKvSfJpc8f+rL7t82eMkd+xjP+wPh0y8ulI5vkWRWGSkOo0c+V7S+FA8S5ewd2fOffWmJwy3gwhfBc3iha6ZMJ5HRy5N4woPu0sZYX1rxdR5j1dqPHZ7aGCz69kZvK6+Ey+fAwNI47Py9kZ49q82fIwKowjmCyMi2u/GlP2ZW7a+TMBNrNa/uzSvZoywAn24KL1iOfPxiZ7qsGMYBgWwkIdn5hNqHlbbagd7nbmeLd7/xBq6FH29yZJv+C63tCoqmX9n/faCM+V/i8VDG/my7TxfAOeDEqidwXZ+62fjpisuDmq7q+ZpOfmjEujOp8Zkse1IGPXKpwr1h9MiLsHyN3km0hxbs1K/V20WRTpS28a6r+sGMIMd0GqQyAfMqSoVm2q2/cxxxzR/CcKc+7K/cFRPGQdHst4PAEGOVftbcd44GuVlj8TgcP9zn4mbn0vdJxtQEXeNPqhpCTUArRUyTxCxe3Qe2vrhyxCIS0xEmi0vLPqYKEy/5mhnIJ/CqdoWhpVhk0rFfDNdQ+612T+65PrAoi9WisYim7sQhM/F4/DT39le0y3KANOLTWFOyPjS1VY6HRPBhRjZomkfQVVdCL3NSkfnkCwga1wtvSlVnp7jRnmoHfQoC8+zjs5zOVOif24CfW4cZK+c3ergCAe/ZrYSNOckZIVYsiaAphKoqZ0CUK2uwzn6yaHa5byHh8X1G1uG7w7IUPxCG1zEHl7pSBy1k71Kg3RCVjmBgVUhheyba4nnMD4YnTBBr7Z/oZS+0sJYQbiQEjto6BNv6eRs06a3PMdm+ZWDi2wgXRE3eeBBRpc9Q4S8beNZN74opjsUdnvjIS5RzoAf/oMgHa+/jvepf8+9ga4oVgMWJnkijvlXtmNnW0DDYIecnxcWW8iPe/rnR9TK5hyITH4Hne/uioDuIKBYM5YaemytlUzKuGqGtvtF2SIKEMUTkB7L7CFAbTKaNB9af9nwNXDUY0iU82TJ8T99dMHpBrt8rYMbId3mwvxQ8axMUw0BiIpFvYOGZBWfvl9PnkHCMJ63Z0vrzBxPXmUnxAhXdjYtnHxDJc7jreCkGyfG2Tn56L93etQWwFjMOT4ceheVVhjgOwzouHbDHAuZ8EDUVg+2XmPsJ9ROl3GujRjeT5NCgYAdpEgA7kYNhzRu0hiBCqu7JDJflposIrTfKFtMG2UIeR8+ckSXRhuiliPFAemUDZOh1F3qKlhTaZsqmjP4Ptom/s/H+Gf9T430FaNgzdkH4/fnR0VdID/x81zBzb/RP6eSrrNU3EUpc793wiAoeAf2xmLhibZlVH8vvxD/J86tDO/gBtk2QfWwnGIa/5qDKvELu8puTYaaUW3Ma/j5bn0P/CkBG5TfBP3dk/ZGLc7fHHsStHHQdgAaIVA/rD12ZMoVHnZmfQfGa21BXLHBW9DTM30P/3siTUe7sRQWWdBXl51u2U51hHy2FaafGnYP/C594tFMK3PvcfBz7qGfLvmll/OzeowWfF2DdNJjThI7b4zok8ejd+mPolvNiKt9usWddPD71jEq/0Y1+PBXbmf5zaXSdricJNOel9nnggG8ABdSvRKaKeH4/OEpUT3cCdYQH36mkH8pILcxqF/nh3DDQWEVbLalokc0MgJ+qsNvoj+WJIKwsYuBCktKZbuvgGMn5gfY74U7qhHGX2lBAAwafWaKKjhZcH3hpJuJRt4YsPZDZjl7kuJ2exSv1JwOWoK+IrwXQuklKm7YXFTqUplFA5UvtUkIVqPjJdpGieojlhWy2Vzpt4fn6C+IBmH4F2+23AzHqNeaDj5su2gvKR+SH4Z0qhYZas+9Oi5RvJ0P3PjQ1bmwkwFpRrV4+CgJaGdPte9MBdT+jsPwSsnWk62MZrW38oD/4aRoUazz0Zhrdck6NbyjPvvSWGgvt2b56tc9rXXee1WuI2Wr3I7veD3HwqD71cZHVsqMjCIIhp9mAHv041OC9vaMdQnpsNzix1YjJXb4f3r19POcBI/s7LmxNa+zR1FghWP2hUysgkvLN2jklicAhHwMXw/O8tJeG3ZnAjwvl4GFKDluVTrb+s9g19ICldH9At9WBR1DR1zGxS9e0HGoqmc1v7o8izMjhKXsq7u6bTgismsMDAkFluuiF+KE8rXcKutFkWoYfqsy2OwhdWcPyokNTHpbz+fkupvfoRAhgLPpTuMz7AR3hzpxLs8YfuqRikLiM7VwOl/g7XJemICzE3wKGdB//MENjR0XmagXII3klB3bi+rIpFyRdfbuBhZCUFSqzCZOZwF/wXCF3J7dWcFHP5U37fZbpGgpOK9vICOaUG8bTuLCG1w5AzAYw4orj/oSJRqoLgcQI1B08y4gObiifGoDTg37oyt5IRLQWFwf1PN5wFrqZ4GCOIQBdf40TzyPW4TkSGMxyYDRliXka6kgAcDwqdpChIBRus3NanzN3jDZCnZVI648VzeMqOA+3SlvT5jTqvJpKn4zovvcvVKBEnr431wxrNhvGnibtzKCGR3NTY9x0QYHe1hvZXfQNnonHOocGa2nnVSJfojuaZyHhHlkhUyAd32vOhMbJTOdX0Z1w2/6q1K9eLGdqRQ1+r2eyZls/7giiQwt9920UOf9cPOLyrxHlYqrr0DBfVVDyLaQ+Mfow5PQdcgtCFDAxJceehfvCxxBM99sv5xHTC00sjgPFKmEB4gNMQ3BuvifahzBXrSxrLXG/S/YpWwbKUSeEkIOQl3KnhUQF9FnBObr5CRMIO5l3cIH53Kvpu92L+wCyVa+ovyvEFCi/txXzDlm2rH4WyN2mqgBMFnZkMuEPCPfnSxrbRQRYmWi8pzaTKLwr99Y8Ph4JDUVreaq/4T3OC8TMi5mASyXZZWQ2mDYBASCy9XPxJhIhal1zgHB3+jUK5tZUc6wIJyZsZGBymyZ+eWAAclZuacmT1ioQdTpUWgZUT79CCEJyAB3x66sLxkbg/RjOixo3H53MYqXr5+5nQJQvtkwgxY0zI1QnzwQ3+rMuiyESiRdfNe2kgwP/MmOQvwB7/ckv34N4ryAQS86iuwQzmFQj7xiQ02D4B8NvwLXKX7zUUcNyr6rvyzA0NZq5TelZ6opCfIc1dU+3SbVvUvkhpTYdaZWgly25NO1t3F3WDAdGscIHqDlHgLx45DpWFTjxyPHswlSs2mmraJN5dS/741KPDrt9vsE4JsSRhYgBbVra78DRfDDo+P102DI8U/ai1d/XZnJ2AVDBRh0ZLDsRv3W5IcCNbruMDzt4CZKLlmfVdwwJL7t3FS/RtzsYd1TkzvGLhbRERgl39AEcOxenz/tuHsUPS6XHu0rT9y2F8xiPRjrZexEvtZ2dPSVft4NLM9TFEWW7my5Efs3ZtknDhUE6jnPSopQQJLgCmiJ152eHOqafKyEu959pCE6X0EtjRdRKWRVToKiGtCIycE9/McKKGaHPMev1pKbvboC+4Q3Oj1sdQXXopDL0nq+/Noj5e+21wA+OZHgigKky//Ep8CYuoJ3zz8nDnzfqPz4Ov+g/v7f/7eMy2FB58b/8OfNPtfWffv+PT5Ia5xX90TUJcNb9Q4MtgQ1D5Z/AERD9WjpVCGiluBcM3lOBr4BoEc73eBG/3/Fdg/FTwvgHpXWRLVjzHZi2Tq08QlEGHsWAAzjS49SxDiW4lH4+7UtfJItltllDHKSEkYMvU2+Rq/kDe59W34PH1rgMOOdJEYH5J7jPZSigpI9diV/bA/iuDaLiF7+jgrrQe0epilcyboUlyXtjbcgOwFQzvo/7C8jfwLvSh/h2iR3HRLg7MjlWifInlkFinPqRMPWCBwBOmeK1hnagtwF/1s55d2jYlrV29mzo3/wkGC4B6vcXkdBgGN1Dd+BLqs8cKuNvDCHvMdzmpOHoCvh0SUd42SMvukXb88aeqp7DreWw9vQLpic6idoFwhpAnQWmZ+jxAdg95Pg808OvKAuk2whGiTxf6sODNqjhrLL11KFc9/6KzuVvNxH/jcvO/v8su396oqXMwfc/74o5+k91ulBi8RUNTwBa/Pqxkze+pkBZ/rUQSWiYTjNKfW601jJg5xQ0mWhm8WWoP134dAYYyrbScwzFwYGqN+MJKFG0xVdebtn/6MMgHJ7LoxQoRnkrFs89UIpX+OLCF1a5HH+0mF4L8cDHiMHauXOrF/qlya0Kfpq0siBe9QD77/Z2QQfMfkhje2/uZxQqPfZaiBmUwMfID+QTK70YCzzXzgJcYnr2TL/yMraiG4Fs09GHt2XGwBgsoHwGfGFgLGTTPIehoYgWNQDc57ekJfmg/9INgKaLEvcxEm23Z5gmsHwHTvdc2otSJo78yFE4cKYOSr4Wxg8JTyxavSYgu1nyAwS4/v6+oEFFmO8g7QUXoAlEWMUP/5XT1qH2p82AoTHTolLdH0B4XI70t8jSdyqDs6o3XCoINhXh5w8KAF6iZRTw9Ljc+pX/GwIk+4DIMEU4T6F/1gPjnqeVm2Nl4TiuE1/7ZPM/aclAdZOFfceYlwQBYTKrbRO9hTToc8lY+dKoCr1FoUWF2hFUGP4Xr4/9iV4UnCoMOCisOJlumB0CxZQxXCERkvj9xYBbCnIpKEZ6BNDlc0/Mgissm3kX4Dlx94u7Be9VAu77IfLgFM2r9/ogXesD8vDI0wHIBp6PtghuQNvUbTenQw0wpw1DW/fuDkaF+ItT9s/e6fqhb9RXQn7mS25f9IdjtUOVqrjX3skXyTRPW2ea3gzIgDsaCsDYWJSf5z3VGTBYkO4PYKupoavgR1m5YiI6AG5fevlra0KtsSO+WYBH3nS5etzqT5U+urFeRAVxIoDcgsdVxNIyOMa9X5H3DWQVNLRaXeiNboIqZhkVR9VBpvJe/FmvOp/cQVkNEiol/k53015F9C9c0If1Xc7/t0dU/B9WHQh8B3AfWHVUsgw2FcgPDcf/8S3K/JLzDPh/YZ/uvEgzY7gc/bTr/D4rGLQtiLXYO8xA9OQbn7ymFEAH/b4ATwyTriCKHHB/T198I0Fvsa4yb9B6S8ell3sps15Mx93h/qaIVgmZBPVf2R7/8f3+D7ZHTP53Aw3xdA9L8IRLYatClwO4lMaFN2E8Bc7FAe18w0PkZzBBZ+mYVu98BzbgWsmp8gCrZukAU0ERkvgSvcM3+r/9Z92akpMHon14I+N491+GetAAtA1o6aBVtSo3B47jABuj3s13DDABTyyZsyrvCYQqlIIFxbNFEeWTj826vfDkw50M2KZAlLQj64vINmiNkUd84TRH3nbrTRUdxIZmGIHwOSidvaZ6CUzTiPbjx4JVHNlxmnb7kqrP5+YbjlznD5OMP3zm9gBYWEG09W9f+mlDhhlR5iBjsrZ8+SuP4h/+979vCh1+/rc6lZ8531nkVlWMDa4OxtL1JTjxpEu0C8QgjyexbtEq4N/3DqJWR32qsFr/SFoq7gNvGUewFOgnvdTa4b0Pehsy+XWo6QC00VNkv1OtwR/swqhGeCGpP/PyhPih9y+AGasRTlgMfDYPefJK4jbNAKwRpNqyR2aOQFWfCz95YlUrSY9pSAtooKpqBTVGU0Wg2NM8AAShr5Z7Koofu+LG3G6f7WJgXv5MQELtAQmeIJAbtkOXGQ6gHXQvagpu1SsZyEDPDZ0J+El4g94ThBykVZidh4qPciNut8ydyVtVntC3SiA/AewaBA0NLCKdBJD4hXv+8NSgXuBr/dOlYiWwStlWwTf+Q6pUNtXAQ2ytAcNCKQQqjbJH86F5a/4tQRez4ysRDNm5O0l6KAYOwFHrijcnEQWQy6in3djUsMXCsTy4X+OboJDRAOkiYDQQIjIR+5KFl0wtkJYWgIrDbuq/Vmr/czH9nXXP9J8gjDk2KWBaBp+r30H8juwhzSDlh1jLUt2WHF18JPauu6ULNErZ+RozIKMMU88jrfVerqH7FTbwASrGVy3eas9/e7jKhwR0G5+Yt0h9oGKMfGzJVnlAt4tCosCqkAu58rg7pDAatf6FhBOxJk+45GU5O2Z3TwCUFykT8l1BV6bntMPNAI5o+UseQSrADHAiDI66B9QgK1jQ9661f/4DqY2YtgPC7vy29lS+dOr4/iJVj0/85w59p5oH2Ivzi+Yp9qiRdnPPyr4vel8W5KXOqdpW+MF8nbFfUp9GcuzrGSh6WfrbvrfLlz9jCRruIMjwklrErieqrvJ9+MWg6lJjfgW+2kUKq3v93i1E0EF3FGo+BiR9DMmyID1Y8lBSxib1vGhaIW3CldUtFfL3m2VmxvdMNuGAD32k7T2iMC7EVrS/2jw9WN1zfp1762Wq1nmX+l0p8cIDsQdwetggLtXxWafn1a/O+ffOG+q8zm93eIC635sNNcq+Az3MelT7LHEgAiQCSM09pzMUO1hJyQgqCcr9AYQVqzaF5TQRbmzjfokMGlEGrfJCr2elInifgUvaCMDcvBvDpT/9kYEQ/MZ9Pj2lAKIBocHjlI8NnO5iZCPi8G3daE5eRYH3Iw0xRJxGotXtC3AiGQG0FRE6YVn6kK52aS51k89oPYu7aLnjS+uI7OSAdYUxd66W5Wd6vF49MkL+WXLPauO5QDKL6uiB8ABJ5/nhwCbPZZgkN14geRsQPUitKLbHQ+8PhS+WV+eT4hMwhVBA/g5TSV8hUH5U8CIf3lrsqcrPT3F/C17dyl5XoJK3CAT3PB7QZF00uo8pmEAacdDIePFcR7o8w18eUCRPxJd3YQ8L5K6OdSm6JR8tUGBgG+0uvRPZT/mScQFJo21ekDt1QvrKAC5A8d/XvPusaqA2Vrj3hImqqP+FmmYplwX+//cdLbLwX46W4ZR3Wr7zMuQ3CuUrvKEaKyb4GmtyrGGdY0dnXI0CiPt1tFV3bCDknXXlm1rnkraXrfUGOR38vdrkxeKqLxf5l0qXf/+2/s5NzvgXMhrLwLwJOG6Yl6FNAaEEApFX6r34jr6l2Z/kBi1Bs8xqIDVFpfDn/ibDrz8GUM/L+Y8dsJr1++BU8aYY+MvmssR1MERqB7wqpsbWJm28GEj3mPc3ugUo+Et+LPdVV3DZapf0vNnfBtrwcnpywLUgqVxwyGbXwMXvux8cbymeaW68q/t/RkDCv/37t+bYeTAEqUIMYmVk+iuLYwWxQPlX10byz58gP5tQX/15R3wJevT6c1uN/sjtlMZTVmD40//bny7v994Tgy9VPFoIuom9P+wN7YTEKyHUaoEJIZEhd3jZwKEkown4Bz5v8BgKCW/KQBmzUF5+iPtDfMc5MKnqUADZqTTw9543ti4yoeWQLD6Am/UF9h7w+nyd3h5J4nfbvkLJV0ouToLzZIg9aqQWwXkdBgpA7SdtNjY1mKByhbudhudmkCa9TiCYxlmp9PrArYFpBQiKqG60Iv8+gZluVTxrdYYTdB1JH3RtJzApLjju9dbewutWUM0iAIg0YBjuJb8hJQbnHtpd9gHj8VllOnImA5W5+Lqyr+YNlnBtZegIWTms3q+/fn15uJhS7XxM+vFU2heOnmCnMHZnKTMaaSGti8vzGuhfB5xM733AnwM05iE6Yhc9boGJVLRmu/V83B+59UxOabi3pb+CTyp6SAN8+gbGNXdn+Tzt4EIhNrC9izh2tswj5aVYYpf9e3vnhbm0r683g46QbwfpGU0mOODpJLZjE3Ajuyb6N9WDCOkQuYMz4OHgMugyKDlBJ+vx28LoEaE7ZHM0gG3wvj9ocIPqJbXleRtESqVz74x7m8sIoI7jJ6QuQeBQiGH5mPEQr5KL5Yd1rNQpYCpzLqaSd2vVSzZDUwnEARat/mF9L2B+iyjBqpIuV3oQTn78Hqs1L2VPWRcoD5delTWrdKfgHdzh33hBzc7wMvZiSWxk2XgAxEO46vXq13ffIYCH9flVRAt2OrDzvczVXIfL7f7SfvTPV9L/YDv614tpCeCNJUNH7Tvu8V9/MbnYv15MHwcCu3hFowNZHHGO950AleLl0Yq9CYy1HwQB6KuoGALkENVFkWiGmJg5QKSMdJqmGE65ehzA80J6hquhbWQP9i2F1rZvRHD+QCGt2vithNAFijm62icBBliRX1H15AWfwt3ffmDvxvjv5aVtlu7br8XfHYiBM2DJqZEWjRkEavFf77lPTMjFqudqO+7b0ydAuOukjrNa3RrmDR3/jj7Bj1MVNeNlIJgtPeiyIj6PP0IYALuLlcdLolwwMlqntE/KJ9IwYD3rVqzMkbnuzkUJ1PO6BfSFcjJw8u35136V+i5Aj/YDKulojbeHDoM9SJO5+yvCTzT3UGeZj9n3wp5v7QBZfYSGF/o+gHewg2rrbVrJXicPHKVO9+B1+dJYodH0BOti8CnPmdU8eGvfn5bvdxYCaJQG9i5fJC+P1W0EaY6++IAsSbH2evabz6eGTLw+fwBhgZeJe/UJoIGWAysVGLs9K2L4Cxu1uCfG8PGK7SM9FMi0gjyhFJsqh8UIXb5n/sMvKTnETVkDNxQKfgMgf7Z2k0Km8wc8TOfRuQandlbJOHdCgtwji8GBbHwRHZnR0Ft6Tg+DQsFZXuesaaoEL961/cuKRPrwkzfYyN/O+LiuhYYOi1ABqqhpyxaBFDWK9z/P1K6NAmKwrh1ye+QmcFwmYBvctn2h/z4mXVChz677rqi+fA/kNwukFaBY+CihxCZzDodrHUSEgLGbwuhphGB6a4Ks4D5GiQiQGZ2y2cq4PW+AY697CSOyvoA4bNbLiuLI2DILkuV0VUBOrqYAEWI1sOy+DGQ7A8VRHO6jQ1EKWITAPz31IM68ZBhGriOpNt+zcKbEJRy9fjjYza1R1kQ5YCw5EGUxQ7fXiHt4LHmCcM8OCyHlS5hUQryyrn67WdPHx5CKu9dsW2pe6AxsoZic2h7oW7MQNyy69sB6jh1IwOmEeXj6I+LAaoNVcV4hwPd7QRiqg5O1daKdCp5eJRvtnn0SFCDrMFh6CfZAf8nS+9xmbAlfiR7oWJgnDg7Gr7nOiofwdC0t5iQsCcE3pmgOCqfhjWZdk13U5QM3wVsth94Wf5AvYdf5SXL5l5a3wlIGMJvXMpNF7RmBtBrJqOibNc4lHQSKP2cxRp/tA/tIZC7d9zlWuitu+fEXfRnf5HGmWvFi0d5Am4BiGN5B7FAfisfrXYEOi7k5QBR9DmHjauV2ZONsWgDOJ4LATzDEnkFR1okwOWKB2WNNhMG7kpFBjE17D3/ttq4XAgLfVwoK+QT0E5B/JlGBVp3zHV1+0vV4gkOrfnQ7Bw53z9qK5hVbKY9FYqDhoqz/lufnI6ocZRwA+bbuX9r/IPFPLyjSFGA/k4T566MYe3PLSvl54DCK8u6fexjl3nhIAx+3WstNuLz9pfv2XmZ/HzfW/187Nw+/eilwoamqbcM6W3K5j2jW/WOc/K6SD/lwgvLLZSgRfzuemoDIdDJ/2jaMBUIcPBMjE2Z0TXyeBboOBgc0zbY/92Hes5QN2SiBvrKAeJkf1v31wHnhrU4PFFjkcOmo6wtyeCOhj+Fb5StVYOufFyVtcRUIGmsH/7hyiCzlFWlB2/2eRrsE+oLD9e6Q/qRZh3FdTSLLH7M99X90ON41MAQST2BFM6WEUQCTOnD6mg9IXLW6eoqJ8868gR8fb97Y4Qhg9L9y/MIT+DtvAq9/yd4jS7kDK9ZeU1m6DNTTOKWC/D1RiOMTnTQ4Y29CxvIbK6joH7ppNPbX9AC7TDB/psaBx3RaAZGBKphCzidkJCw5hMnAdpns9mKB+aq6qO+WMkqm5c0KeyC73a5xURkgs0BLslQ6rtrvtvl0hRMyJLvh8RX9cPpmoIjoTVW34aa6w0XD1Wpl2h/zY6BdkxSM7Adi3hbIoGxsvDrL2U7yFXyouOOgM5OTCnJb4xe0jmcbS6EfAK5AQic8hRBZYPxZJfwsnqtSjW0JauwuQHCi8Z7x+cY2d7hLEjC3k3lh6eKrbd+ZIfkQKH7fZXBdTwP31+33hj3I9CoqdkfHa03tyZYDY7u1zalf0AcgaVk+NtDcRrwyJSc2aHmruhWsT1jNWcXRD7pGrDYvEuInMUFnAR5KjLJ1eTOH0oGd+OLS8JsrA40IaRvXqIWq3w08lwkCCsY3H30i+/WMN5Bsk+PKucfFKF2CnNVmKJ6JPapm4Y27YZ+RurtqDTfR62hJoTySkJ0hpjL6X4kW/8//CwMCqvc="

ASSETS = json.loads(zlib.decompress(base64.b64decode(ASSETS_BLOB)))


if __name__ == "__main__":
    main()
